### ISSUE TITLE
Bug in SBV translation

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-script#101]
[AES_min.cry.txt](https://github.com/GaloisInc/saw-script/files/127176/AES_min.cry.txt)

The attached Cryptol source file contains a portion of the specification of AES related to the S-boxes.  The property `SubByte_eq` claims that the included explicit lookup table calculates the same values as a sequence of GF(2^8) operations.  When loaded in the Cryptol interpreter, this property can be exhaustively checked, and proved with z3 and Yices.  However when we attempt the same proof via the following saw script, the proof succeeds via ABC, but fails with a bogus counterexample if we use z3, CVC4 or Yices.

```
import "AES_min.cry";	

print "ABC proof";
prove_print abc {{ SubByte_eq }};

print "Z3 proof";
prove_print z3 {{ SubByte_eq }};
```

I am lead to believe that the SAWCore->SBV translation has a bug, probably in the GF polynomial operations.

**Comment by brianhuffman** [comment]
There certainly is a bug:

    sawscript> print {{ SubByte 2 }}
    0x77
    sawscript> sat abc {{ \x -> x == SubByte 2 }}
    Sat: 0x77
    sawscript> sat z3 {{ \x -> x == SubByte 2 }}
    Sat: 0x22

`SubByte` works correctly for arguments 0 and 1, but it gives the wrong result otherwise. I'll look into it.

**Comment by brianhuffman** [comment]
The problem is with `pmult`:

    sawscript> sat z3 {{ \x -> x == pmult 0x01 0x01 }}
    Sat: 0x4000
    sawscript> sat z3 {{ \x -> x == pmult 0x80 0x80 }}
    Sat: 0x0001

It appears that in the SBV backend, `pmult` gives its result with reversed bit order.

**Comment by robdockins** [comment]
Indeed, reversing the bit order fixes this problem.  I'll push a patch for this soon.
