### ISSUE TITLE
Run tests as part of nightly builds

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#1033]
We currently run tests on PR creation and merges to `master`, but not with the nightly builds. I'd feel more comfortable if the builds we were providing for download had been directly tested (even though the above tests _should_ always cover the same code). This would also give us an option for adding some longer-running tests that won't hold up PRs.

**Comment by robdockins** [comment]
@atomb, is this still the case?

**Comment by atomb** [comment]
Looks like this is fixed, as evidenced in last night's build: https://github.com/GaloisInc/saw-script/actions/runs/982239117
