### ISSUE TITLE
refactor cryptol server methods for saw server

### ISSUE THREAD

**Issue by pnwamk** [GaloisInc/saw-script#1050]
In https://github.com/GaloisInc/saw-script/commit/4b452cb6bdc59395388d76e7148c9cab4fe6c75c we duplicated some code ([here](https://github.com/GaloisInc/saw-script/blob/4b452cb6bdc59395388d76e7148c9cab4fe6c75c/saw-remote-api/src/SAWServer/CryptolExpression.hs#L117), [here](https://github.com/GaloisInc/saw-script/blob/4b452cb6bdc59395388d76e7148c9cab4fe6c75c/saw-remote-api/src/SAWServer/CryptolExpression.hs#L132), and [here](https://github.com/GaloisInc/saw-script/blob/4b452cb6bdc59395388d76e7148c9cab4fe6c75c/saw-remote-api/src/SAWServer/CryptolExpression.hs#L159)) to make merging all the submodule updates smooth.

Now, however, need to remove this duplication by exposing the duplicated, more polymorphic versions of those functions as illustrated by this [cryptol diff](https://gist.github.com/pnwamk/de62116779071d45b8c2f17d3245b5ec) and this [saw-script diff](https://gist.github.com/pnwamk/e5d2525b6998ed3d678bb04862715d57) (modulo any additional changes needed based on other repo activity of course).

**Comment by RyanGlScott** [comment]
I _think_ this was done in #1109, correct?

**Comment by pnwamk** [comment]
Yes, thanks for the reminder =)
