### ISSUE TITLE
Remove jvm-verifier submodule

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#1056]
Pull request #1005 has removed all the deprecated java verification commands that were based on code from jvm-verifier. However, the `jvm-verifier` repository is still a submodule of saw-script due to a couple of remaining dependencies. For example, some tests in our integration test suite rely on java code and other artifacts that are stored in the `jvm-verifier` repo.

We should address the remaining dependencies, moving test code as necessary, in order to completely remove the `jvm-verifier` submodule.

**Comment by RyanGlScott** [comment]
This was done in #1060.
