### ISSUE TITLE
Automatic rt.jar detection is likely incorrect on macOS for pre-7 versions of the JDK

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/saw-script#1062]
I recently came across this note in `find-java-rt-jar.sh`:

https://github.com/GaloisInc/saw-script/blob/f8449a13822180cf7338f70f68f213407067728b/intTests/support/find-java-rt-jar.sh#L3-L4

This came as a surprise to me, as I was under the impression that the JDK consistently named this file `rt.jar`. If this is the case, the logic I implemented for automatically detecting `rt.jar` in #1030 is incorrect when combining macOS with JDK 6 and earlier. We should verify that this is the case and add a corresponding code path for `classes.jar`.

**Comment by RyanGlScott** [comment]
This would also affect the `crucible-jvm` tool in the `crucible` repo, where I implemented similar code in GaloisInc/crucible#636.

**Comment by atomb** [comment]
Given how old JDK 6 is at this point, I think it might be reasonable to simply state that we only work with versions 7 and greater. Alternatively, we could identify the whole set of (JDK version, OS, rt.jar location) triples for historical versions. Or this could be the reason to keep `SAW_JDK_JAR`, as a way to allow the tools to function with old JDK versions.

**Comment by RyanGlScott** [comment]
Valid points. It's perhaps a bit heavy handed to error outright if you use an old JDK, but we could document the fact that old JDKs might not adhere to modern conventions, so you may have to manually specify some locations (be it with `-j`, `SAW_JDK_JAR`, or otherwise) to compensate.

**Comment by atomb** [comment]
> Valid points. It's perhaps a bit heavy handed to error outright if you use an old JDK, but we could document the fact that old JDKs might not adhere to modern conventions, so you may have to manually specify some locations (be it with `-j`, `SAW_JDK_JAR`, or otherwise) to compensate.

Yeah, something like that sounds exactly right.
