### ISSUE TITLE
llvm_field in python

### ISSUE THREAD

**Issue by jldodds** [GaloisInc/saw-script#1073]
It would be useful to expose something like llvm_field in the python interface.

An ideal test case would be extending [this one](https://github.com/GaloisInc/saw-script/blob/master/saw-remote-api/test-scripts/llvm_struct.c)

with another spec that uses a per-field constructor instead of the current struct operation.

Ideally we also show that we can specify only one of the structs in the record and leave the other unspecified as well.

**Comment by RyanGlScott** [comment]
I agree that we should support this, although I think that's now the domain of [`galois-py-toolkit`](https://github.com/GaloisInc/galois-py-toolkit) rather than this repo.

**Comment by pnwamk** [comment]
Now tracking here: https://github.com/GaloisInc/galois-py-toolkit/issues/4
