### ISSUE TITLE
Feature request: Support modifying arrays of objects

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/saw-script#108]
Attempting to verify the following `Test.java`:

```
public class Test {
    public int test(int x) {
        Object[] arr = new Object[20];
        return x;
    }
}
```

Using `Test.saw`:

```
Test_class <- java_load_class "Test";
let test_spec : JavaSetup() = do {
  x <- java_var "args[0]" java_int;
  java_return {{ x }};
  java_verify_tactic abc;
};
java_verify_exp Test_class "test" [] test_spec;
```

Results in an error:

```
Loading module Cryptol
Loading file "Test.saw"
When verifying Test.test:
Proof of an invalid path failed.
Counterexample: 
Allocates or modifies a reference array.
saw: user error (Proof failed.)
```

Arrays of Java objects occur in some code that I'm attempting to verify, so this is a feature that I would like.

Interestingly, using the `java_extract` style of proof, this works:

```
test <- java_extract Test_class "test" java_pure;
let thm = {{ \x -> test x == x }};
prove_print abc thm;
```

```
Loading module Cryptol
Loading file "Test.saw"
Valid
```

Unfortunately, for my code, I require `java_verify_exp`.

**Comment by jpziegler** [comment]
Note that including `java_allow_alloc` doesn't help.

**Comment by atomb** [comment]
This particular example works now that #114 is closed, but the more general problem of specifying the expected final values stored in reference arrays is still open. I'll leave this ticket open to track the more general case.

**Comment by atomb** [comment]
We should ensure that this is possible using `crucible_jvm_verify`

**Comment by brianhuffman** [comment]
It certainly should be possible with `crucible_jvm_verify`. We should close this ticket as soon as we add a test case for it.

**Comment by atomb** [comment]
With `crucible_jvm_verify`, we can do the following. Consider the modified version of the code that includes both static and non-static versions of the method:

````
public class RefArray {
    public static int test1(int x) {
        Object[] arr = new Object[20];
        return x;
    }

    public int test2(int x) {
        Object[] arr = new Object[20];
        return x;
    }
}
````

This can be verified with the following script:

````
Test_class <- java_load_class "RefArray";
let test1_spec : JVMSetup() = do {
  x <- jvm_fresh_var "x" java_int;
  jvm_execute_func [jvm_term x];
  jvm_return (jvm_term x);
};
let test2_spec : JVMSetup() = do {
  x <- jvm_fresh_var "x" java_int;
  r <- jvm_alloc_object "RefArray";
  jvm_execute_func [r, jvm_term x];
  jvm_return (jvm_term x);
};
crucible_jvm_verify Test_class "test1" [] false test1_spec abc;
crucible_jvm_verify Test_class "test2" [] false test2_spec abc;
````
