### ISSUE TITLE
Add saw-script `llvm_struct_type` function

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#1085]
We have a function `llvm_struct_value : [SetupValue] -> SetupValue` for creating LLVM values in saw-script, but we do not have a corresponding function `llvm_struct_type : [LLVMType] -> LLVMType` for creating LLVM struct types. We should add it.

Note that we do already have a function called `llvm_struct` that gives you an `LLVMType`, but it only takes a string as an argument and gives you the corresponding alias type (which is often, but not necessarily, defined as a struct type).

The `llvm_struct_type` function will be specifically useful when you have a program that has defined a variable-length struct (i.e. one where the last field is an array with unspecified length, which is compiled to LLVM with an array length of 0) and you want to allocate one with a non-zero array length in the last field.

For completeness, we should probably also add a variant for packed struct types too, although these are rarely used in practice.

**Comment by RyanGlScott** [comment]
> Note that we do already have a function called `llvm_struct` that gives you an `LLVMType`, but it only takes a string as an argument and gives you the corresponding alias type (which is often, but not necessarily, defined as a struct type).

Wow, that's pretty confusing. I wonder if we should use a name like `llvm_alias` instead for this?

**Comment by brianhuffman** [comment]
One problem with renaming `llvm_struct` to `llvm_alias` is that `llvm_struct` is already in use in a lot of places, so renaming it would break a bunch of existing proof scripts.

**Comment by RyanGlScott** [comment]
> I suppose we could always just introduce a new name llvm_alias, and then phase out the old name later.

Right, this is what I was thinking. Having `llvm_struct` coexist with `llvm_struct_type` seems ripe for confusion.
