### ISSUE TITLE
Add support for SuiteB and ECC primitives

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#1098]
For my needs, I want to do a proof using w4_unint_yices and uninterpret these functions, but I can't currently load a Cryptol file that references these primitives.

```
You have encountered a bug in cryptol-saw-core's implementation.
*** Please create an issue at https://github.com/GaloisInc/saw-core/issues

%< --------------------------------------------------- 
  Revision:  ed0d14aa85818be4eb258832115ed77348ea8846
  Branch:    HEAD
  Location:  Unknown Cryptol primitive name
  Message:   PrimIdent (ModName "SuiteB") "AESKeyExpand"
CallStack (from HasCallStack):
  panic, called at src/Verifier/SAW/Cryptol/Panic.hs:13:9 in cryptol-saw-core-0.1-inplace:Verifier.SAW.Cryptol.Panic
  panic, called at src/Verifier/SAW/Cryptol.hs:628:29 in cryptol-saw-core-0.1-inplace:Verifier.SAW.Cryptol
%< --------------------------------------------------- 
```

**Comment by brianhuffman** [comment]
It shouldn't be too much work to add a stub for this primitive that can be treated as an uninterpreted function.

**Comment by weaversa** [comment]
I think a quick and simple stub would be for `saw` to simply define these as `undefined`.

**Comment by brianhuffman** [comment]
Yes, I'll just stub these out as `undefined` for now. Also I should extend the `cryptol-test-suite` to translate *all* of Cryptol's built-in modules, instead of just translating `Cryptol.cry` as it does now.
