### ISSUE TITLE
Unhandled exception (index out of bounds)

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/saw-script#11]
I'm seeing:

```
./Data/Vector/Generic.hs:249 ((!)): index out of bounds (96,0)
```

From the below code which was intended to prove the Cryptol implementation of `crypto_secretbox` from NaCl is identical to itself. 

```
import "CryptoBox.cry";

let main : TopLevel () = do {
    let cry_crypto_secretbox = {{ \s k n -> crypto_secretbox (s : [1][8]) k n }};
    cryAIG  <- bitblast cry_crypto_secretbox;
    res <- cec cryAIG cryAIG;
    print res;
};
```

To reproduce just git-clone GaloisInc/crylock, add the above code to `src/prim/CryptoBox.saw` directory and `saw CryptoBox.saw`.

**Comment by atomb** [comment]
A nice compromise would be to use different data structures for different sizes of vectors. We could use array-like structures for small vectors, and list-like (or even map-like) structures for large vectors.

**Comment by robdockins** [comment]
We deleted the `[x..]` form, so no additional work needs to be done to support it.
