### ISSUE TITLE
Support double pointers in LLVM

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#111]
Currently, the `LLVMType` type doesn't allow description of pointer types, so the type argument to an `llvm_ptr` command can't be a pointer type and therefore can't describe double indirection.

**Comment by ntc2** [comment]
This came up in V2V, but we worked around it by replacing `unsigned char **buf` with `unsigned char *buf` and `uint32_t *index`.

**Comment by benjaminjellison** [comment]
Do you have any sample code?  Will this work for double pointers to structs?  I'm trying to model code that functions with arguments that are double pointers to structs, so I'd like to see if this would work for that.

**Comment by ntc2** [comment]
@benjaminjellison: the code we were trying to verify had double pointers to `chars`. E.g.

```c
void encode(int x, unsigned char **buf) {
  unsigned char *src = &x;
  for (int i = 0; i < sizeof(int); ++i) {
    **buf = src[i];
    ++(*buf); 
  }
}

void decode(int *x, unsigned char **buf) {
  unsigned char *dst = x;
  for (int i = 0; i < sizeof(int); ++i) {
    *dst[i] = **buf;
    ++(*buf); 
  }
}

int vc(int x, int y, unsigned char *buf) {
  unsigned char *buf0 = buf;
  encode(x, &buf);
  encode(y, &buf);
  int x1;
  int y1;
  buf = buf0;
  decode(&x1, &buf);
  decode(&y1, &buf);

  return x == x1 && y == y1
}
```

Goal is to verify that `vc` always returns `1` (when `buf` is large enough).  If we want to give a functional Cryptol spec for `encode` or `decode`, then we need to talk about double indirection for the `unsigned char **buf` args.

Warning: I typed this code directly into this comment and it might be buggy, but the intention should be clear.

**Comment by atomb** [comment]
Things like this should work using `crucible_llvm_verify` instead of `llvm_verify`.
