### ISSUE TITLE
Remove error messages about unimplemented primitives in SAWCore simulator

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#113]
The SAWCore simulator currently prints out errors when some of the SAWCore primitives aren't implemented in a given backend. We should resolve this in a nicer way.

**Comment by ntc2** [comment]
See https://github.com/GaloisInc/saw-script/issues/48 for related comments.

**Comment by atomb** [comment]
This is fixed in GaloisInc/saw-core@671578c1e70ebf86ba57659f8f2c98dfb6d92f35
