### ISSUE TITLE
saw-remote-api: Review whether dependencies listed in requirements.txt are needed

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/saw-script#1152]
The `requirements.txt` file lists a surprising number of dependencies:

https://github.com/GaloisInc/saw-script/blob/226a33d204201afd018397f9ebb7d579ed789a2a/saw-remote-api/python/requirements.txt#L1-L30

Some of these dependencies, such as `Jinja2`, aren't listed in the `poetry.lock` file generated by `poetry`, which computes the transitive closure of the dependencies needed in the `pyproject.toml` file. This leads me to wonder if we can remove some of the dependencies in `requirements.txt`, especially since we semi-frequently receive notifications from @dependabot to upgrade things like `Jinja2`.

**Comment by pnwamk** [comment]
I also don't see `Sphinx` et al in the `poetry.lock`, which we've used to automatically generate documentation, some of which is/can be formatted in HTML. Still not sure the root cause, but I suspect whatever it is might explain both these things.

**Comment by RyanGlScott** [comment]
> I also don't see `Sphinx` et al in the `poetry.lock`, which we've used to automatically generate documentation, some of which is/can be formatted in HTML.

This is a good point, and a nuance that I didn't really convey when submitting this issue. Namely, not all of the dependencies listed in the `requirements.txt` file are actually needed to build the core `saw` package itself. Rather, some of these dependencies are only used for developer-only workflows, such as generating Sphinx documentation. Poetry calls these `dev-dependencies` (see [`cryptol`'s `pyproject.toml` file](https://github.com/GaloisInc/cryptol/blob/b4e0a7fbe3bd5ea450efc46cfdf0992cc857219b/cryptol-remote-api/python/pyproject.toml#L13-L14) for an example), and indeed, the `pyproject.toml` files for `cryptol` and `saw` should probably include Sphinx _et al._ as `dev-dependencies`.

Still, I'm unclear if `jinja2` is included in service of a developer-specific workflow. I could believe that `jinja2` is a dependency of some other library in the `requirements.txt` file, but if that's the case, it seems like it should be safe to remove it, since installing the other library would bring in `jinja2` anyway.

As a side note, this is one of the reasons I prefer using Poetry to manage dependencies over `requirements.txt`, as Poetry can figure out a lot of this guesswork for you. I recognize the importance of keeping `requirements.txt` files for the sake of those who would prefer to just install a `virtualenv` instead of using fancy tools, but still.

**Comment by RyanGlScott** [comment]
As of 809a39c740f21dffe382badb09d4aa91f71251f1, the `requirements.txt` file is now auto-generated based on the contents of `pyproject.toml`, so the two files are now in sync.
