### ISSUE TITLE
Python names for LLVM values/types inconsistent

### ISSUE THREAD

**Issue by pnwamk** [GaloisInc/saw-script#1164]
It looks like the constructor names for LLVM [values](https://github.com/GaloisInc/saw-script/blob/8f65fd8aec3814e51803560444efb614c9ab225a/saw-remote-api/python/saw/llvm.py#L489) and [types](https://github.com/GaloisInc/saw-script/blob/8f65fd8aec3814e51803560444efb614c9ab225a/saw-remote-api/python/saw/llvm_types.py#L77) in the python interface don't really have a consistency to them =\ IMO we should address this soon and then stick to whatever naming pattern we prefer.

Options:
1. Use a consistent suffix for each, e.g., `NAME_val` and `NAME_ty` (pros: simple, predictable; cons: a few additional characters here and there)
2. Use no suffixes, but places values and types in modules which can be imported with whatever prefix is desired (pros: flexible, users decide prefix to import with (if any); cons: `val.NAME` and `ty.NAME` might look funny, if no prefix is present from the import it may be difficult to determine meaning from code).

**Comment by RyanGlScott** [comment]
I think (1) is closest to my ideal, although I don't think we need to use the suffixes for _every_ definition. For instance, I think `global_var` is fine as it is, and `global_var_val` would just be unnecessarily redundant.

**Comment by pnwamk** [comment]
Fixed by https://github.com/GaloisInc/saw-script/pull/1168
