### ISSUE TITLE
`saw/__init__.py`: Implement `llvm_assume` (à la `llvm_verify`)

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/saw-script#1189]
The Python bindings currently offer `llvm_verify`, but they don't offer a counterpart to SAWScript's `llvm_unsafe_assume_spec`. There is an `llvm_assume` function in `saw/connection.py`, but it assumes that you already have access to a `Connection`, which isn't true for the API in `saw/__init__.py`.

In theory, implementing `llvm_assume` should be a matter of adapting the code for `llvm_verify` somewhat:

https://github.com/GaloisInc/saw-script/blob/a0ce2993da67fc70e8640f5303142d909a60daa7/saw-remote-api/python/saw/__init__.py#L338-L422

Not everything here will be relevant for `llvm_assume`, such as the `VerificationSucceeded`/`VerificationFailed` classes.

**Comment by atomb** [comment]
I'm working on this as part of support for ghost variables.

**Comment by RyanGlScott** [comment]
Implemented in #1108.
