### ISSUE TITLE
inconsistency between a do block and the toplevel

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-script#1215]
There's an odd inconsistency between a `do` block and the toplevel REPL: I can destructure the LHS of a monadic result in a `do` block:

    sawscript> let mkpair = do { x <- fresh_symbolic "x" {| [8] |}; return (x,x); }
    sawscript> do { (a,b) <- mkpair; return a; } ;
    [15:34:27.679] fresh:x#613

but not at the top level:

    sawscript> (a,b) <- mkpair

    <stdin>:1:10-1:16: Type Mismatch, expected: TopLevel (Term, Term) but got: (t.0, t.1)
     at "a" (<stdin>:1:2-1:3)
    Type constructors mismatch. Expected: <Block> but got (,) at "a" (<stdin>:1:2-1:3)

There is a work-around

    sawscript> ab <- mkpair
    sawscript> let (a, b) = ab

so this is not a big deal, but it is unexpected.  As this is not a syntax error, it seems like it was supposed to be allowed.

**Comment by sauclovian-g** [comment]
#1638 is not just related, it's the same bug, and includes diagnosis, so I'm going to close this copy as a duplicate.
