### ISSUE TITLE
Latest XCode update breaks bitcode parsing

### ISSUE THREAD

**Issue by ttaubert** [GaloisInc/saw-script#122]
Installed the latest XCode 7.3 yesterday and it looks like the LLVM output changed once again. `clang --version` reports `Apple LLVM version 7.3.0 (clang-703.0.29)`.

The SAW error is:

```
Loading module Cryptol
Loading file "test.saw"
saw: user error (Bitcode parsing of test.bc failed:
match failed)
```

Here's the failing byte code: [test.bc.zip](https://github.com/GaloisInc/saw-script/files/183783/test.bc.zip)

**Comment by atomb** [comment]
This seems to consistently work now.
