### ISSUE TITLE
Construct a complete type checker for SharedTerm

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#1226]
The type checker in `Verifier.SAW.SCTypeCheck` is convenient, but not entirely complete. It can fail to type-check terms that are type correct. We should re-visit the design and either adapt it or replace it with something complete. However, the preferred mode of use should probably be to construct "certified" terms, as in GaloisInc/saw-core#18.

**Comment by brianhuffman** [comment]
There has been a lot of work done on the `SCTypeCheck` module since 2015, and I expect that it's rather complete now. We can reopen if anyone comes across any specific examples of terms that should typecheck but don't.
