### ISSUE TITLE
Quotes in string literals should be escaped

### ISSUE THREAD

**Issue by eddywestbrook** [GaloisInc/saw-script#1240]
Double quotes in SAW core string literals should be escaped when translated to Coq. Otherwise you get a situation where a SAW core string like `This string causes "problems"` is translated to the Coq expression

```
("This string causes "problems"")
```

which Coq will think is an application of the first string to the term `problems` and the empty string.

**Comment by sauclovian-g** [comment]
The fix cited seems to be in the current repository, so as far as I can tell this one is done.
