### ISSUE TITLE
Use reader-monad bracketing combinators for extending bound variable environment in translator

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#1254]
Currently the term translation monad is just a state monad, and the local variable environment is just one of the fields in the mutable monad state, which can be updated at any time. As @eddywestbrook suggests in the comment thread of GaloisInc/saw-core-coq#29, it would be more principled to use reader-monad-style operations to manage the local variable environment. Following this discipline will make the code easier to understand and make errors easier to avoid.

So instead of
```
translateAndBindName :: String -> m Ident
```
we should use only bracketing combinators like
```
withTranslatedName :: String -> (Ident -> m a) -> m a
```
that explicitly delimit the scope of the `Ident` that is added to the local environment.

**Comment by eddywestbrook** [comment]
Closed by #1928
