### ISSUE TITLE
Support for newtypes

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-script#1256]
Following the merge of https://github.com/GaloisInc/cryptol/pull/1015, we need to add support for newtypes to `cryptol-saw-core`.

As a first pass, we will simply erase newtypes.  They don't satisfy any typeclass constraints, so that part of the translation should be easy.

**Comment by robdockins** [comment]
I think this has been done for some time now.

**Comment by atomb** [comment]
We have an internal example where record selection to project from a `newtype` fails to translate.

**Comment by robdockins** [comment]
Are you able to minimize the example?

**Comment by atomb** [comment]
Just finished doing that. Here you go.

Say you have the following in `newtype_bug.cry`:

```
newtype T n = { vec : [n] }

fromT : {n} T n -> [n]
fromT x = x.vec
```

Then running `import "newtype_bug.cry"` at the SAWScript REPL leads to a panic about an invalid record selector.

**Comment by robdockins** [comment]
Ah, I see.  The record selector code is type-driven and doesn't know what to do for newtypes.  That shouldn't be too hard to fix.
