### ISSUE TITLE
Hashable instance for terms

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-script#1265]
It looks to me like the `Hashable` instance for saw-core terms does not respect alpha-equivalence because it hashes over the names of arguments.  It also distinguishes between shared and unshared terms.  This seems like a mistake to me.

Why do I care? I'm considering implementing a bloom filter for caching proofs we've previously performed, and identifying propositions up to alpha seems like a reasonable thing to do.

So more generally, what properties do we actually want from this hash function, and how should we verify we have them?

**Comment by brianhuffman** [comment]
The `Hashable` instance is used for hash-consing of terms. If we made hash-consing ignore bound variable names, then users might find that the bound variable names they chose in a term are renamed automatically as terms are built. I think users would find this surprising and undesirable.

It might be the case that we want different hash functions for different purposes. We don't necessarily need to use the same `Hashable` class instance for hashing in both situations.

**Comment by sauclovian-g** [comment]
This question appears to have been answered.
