### ISSUE TITLE
Avoid unnecessary unpacking and repacking of `Text` values

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#1269]
We should look over all occurrences of `Text.pack` and `Text.unpack` in the codebase; many of them are probably unnecessary. We should be able to keep values in type `Text` as much as possible, and try not to ever convert them to type `String`.

**Comment by RyanGlScott** [comment]
See also #1260.

**Comment by brianhuffman** [comment]
I have a patch for #1260 in preparation now; this ticket is so I don't forget all the other uses of `Text.pack` and `Text.unpack` that I've encountered along the way.

**Comment by brianhuffman** [comment]
#1281 probably took care of enough `String`/`Text` conversions for now.
