### ISSUE TITLE
Reading a SAWcore file with two trailing newlines results in a Parse Error

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/saw-script#129]
```
SAWCoreTerm 7
1 Data Prelude.Bool
2 Global Prelude.and
3 ExtCns 0 a 1
4 App 2 3
5 Ctor Prelude.False
6 App 4 5
7 Lam a 1 6


```
Reading the above SAWcore term into saw, including both trailing newlines, results in a Parse Error.
```
sawscript> t <- read_core "sawcore_test.core"

scReadExternal: Parse error
```
Removing one trailing newline fixes the problem.

**Comment by brianhuffman** [comment]
It would be easy to make the parser ignore empty lines; would this be sufficient?

**Comment by jpziegler** [comment]
Makes sense to me.
