### ISSUE TITLE
memcpy() from a big buffer takes a long time to verify

### ISSUE THREAD

**Issue by ttaubert** [GaloisInc/saw-script#130]
I hit this when trying to verify a function that basically overwrites a given buffer with zeros, here's a simplified version that uses memcpy() because SAW doesn't yet support memset() with a variable length:

```
void zero(uint32_t *buf, uint32_t len, uint32_t off) {
  uint32_t zeros[1024] = { 0 };
  memcpy(buf + off, zeros, (len - off) * sizeof(uint32_t));
}
```

The SAW code:

```
llvm_verify m "zero" [] do {
  llvm_ptr "buf" (llvm_array 5 (llvm_int 32));
  buf <- llvm_var "*buf" (llvm_array 5 (llvm_int 32));
  len <- llvm_var "len" (llvm_int 32);
  off <- llvm_var "off" (llvm_int 32);

  llvm_assert_eq "len" {{ 5 : [32] }};
  llvm_assert_eq "off" {{ 0 : [32] }};
  llvm_ensure_eq "*buf" {{ [0, 0, 0, 0, 0 : [32]] }};
  llvm_verify_tactic abc;
};
```

Now the interesting thing is that this doesn't happen if I remove the offset parameter `off`. If the source buffer is small, e.g. `uint32_t zeros[16]` it finishes a lot faster than with a big buffer as seen here.

**Comment by ttaubert** [comment]
As with removing the `off` parameter, verification finishes almost instantly when removing the `llvm_ensure_eq "*buf" ...` line.

**Comment by atomb** [comment]
With `crucible_llvm_verify`, this now performs well, and `llvm_verify` is now gone.
