### ISSUE TITLE
"set_base" command has no effect on counterexamples generated by llvm_verify

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-script#131]
The set_base command doesn't seem to do anything.  REPL responses and proof counterexample printing should pay attention to this setting, but seem not to.

```
sawscript> 12345
12345
sawscript> set_base 16
sawscript> 12345
12345
sawscript> 0x12345
74565
sawscript> set_base 2
sawscript> 12345
12345
```

**Comment by brianhuffman** [comment]
It's not nearly as bad as you say:

    sawscript> print {{ 12345 }}
    Assuming a = 14
    0x3039
    sawscript> print_term {{ 12345 }}
    let { x0 = Cryptol.TCNum 0x3039;
        }
     in \(u194::Cryptol.Num) ->
          \(_P::Cryptol.PFin u194) ->
            \(_P'::Cryptol.PGeq u194 (Cryptol.TCNum 0xe)) ->
              Cryptol.ecDemote x0 u194
                (Cryptol.ePFin x0)
                _P
                (Cryptol.ePGeq u194
                   (Cryptol.tcWidth x0))
    sawscript> sat abc {{ \x -> x == 0x12345 }}
    Sat: [x = 0x12345]
    sawscript> prove abc {{ \x -> x == 0x12345 }}
    Invalid: [x = 0x00000]

The current base is used for printing
  * cryptol values
  * sawcore terms
  * witnesses from `sat`
  * counterexamples from `prove`

However the current base is not currently used for printing saw-script `Int` values, as you've shown. And I think you were originally concerned about counterexamples printed by `llvm_verify`, is that right?

**Comment by robdockins** [comment]
Ah, I see I simplified my example a bridge too far.  Indeed, the initial concern was about counterexamples generated from llvm_verify.

**Comment by brianhuffman** [comment]
@robdockins can you paste in an example of an `llvm_verify` output that illustrates the problem? I'm feeling to lazy to come up with an example myself ;)

**Comment by robdockins** [comment]
Consider the following SAW script and LLVM assembly file:

test.saw
```
llvm_module <- llvm_load_module "test.bc";

let prove_mod_add64 = do {
  in0 <- llvm_var "a0" (llvm_int 64);
  in1 <- llvm_var "a1" (llvm_int 64);
  in2 <- llvm_var "a2" (llvm_int 64);
  llvm_assert {{ in0 == (9223372036854775808:[64]) }};
  llvm_assert {{ in1 == (137438953472:[64]) }};
  llvm_assert {{ in2 == (9223371899415822336:[64]) }};
  llvm_return {{ 0:[64] }};
  llvm_verify_tactic abc;
};

set_base 16;
print "Verifying mod_add64";
llvm_verify llvm_module "mod_add64" [] prove_mod_add64;
```

test.ll
```
; ModuleID = 'test.bc'
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-macosx10.11.0"

@.str = private unnamed_addr constant [8 x i8] c"0x%llx\0A\00", align 1

; Function Attrs: nounwind ssp uwtable
define i32 @main() #0 {
  %1 = tail call i64 @mod_add64(i64 -9223372036854775808, i64 137438953472, i64 9223371899415822336) #3
  %2 = tail call i32 (i8*, ...)* @printf(i8* getelementptr inbounds ([8 x i8]* @.str, i64 0, i64 0), i64 %1) #3
  ret i32 0
}

; Function Attrs: nounwind
declare i32 @printf(i8* nocapture readonly, ...) #1

; Function Attrs: nounwind readnone
define i64 @mod_add64(i64 %a0, i64 %a1, i64 %a2) #2 {
  %r8 = add i64 %a2, %a1
  %r11 = zext i64 %r8 to i65
  %r15 = zext i64 %a0 to i65
  %r18 = sub nsw i65 %r11, %r15
  %r22 = icmp sgt i65 %r18, -1
  %r23 = trunc i65 %r18 to i64
  %r24 = select i1 %r22, i64 %r23, i64 %r8
  ret i64 %r24
}

attributes #0 = { nounwind ssp uwtable "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { nounwind "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #2 = { nounwind readnone }
attributes #3 = { nounwind }

!llvm.ident = !{!0}
!llvm.module.flags = !{!1}

!0 = !{!"clang version 3.6.2 (tags/RELEASE_362/final)"}
!1 = !{i32 1, !"PIC Level", i32 2}
```

When run, this produces the following output:

```
$ clang -c -emit-llvm test.ll
$ saw test.saw
Loading module Cryptol
Loading file "test.saw"
Verifying mod_add64
When verifying @mod_add64:
Proof of return value failed.
Counterexample: 
  %a0: 9223372036854775808
  %a1: 137438953472
  %a2: 9223371899415822336
return value
Encountered:  9223372036854775808
Expected:     0
saw: user error (Proof failed.)
```

This output prints the counterexample in decimal base, rather than base 16, as requested.
