### ISSUE TITLE
Cryptol-saw-core translator produces ill-typed terms from polymorphic recursive functions

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#1318]
This problem was discovered as a test suite failure in #1317, which bumps `cryptol` to include the new `sortBy` function in the Cryptol prelude. Here's a self-contained example that you can do from the REPL:
```
sawscript> let {{ funpow f (n : Integer) x = if n <= 0 then x else funpow f (n - 1) (f x) }}
sawscript> type {{ funpow }}
[18:30:50.891] {a} (a -> a) -> Integer -> a -> a
sawscript> check_term {{ funpow }}

Stack trace:
"check_term" (<stdin>:1:1-1:11):
Inferred type
  sort 1
Not a subtype of expected type
  sort 0
For term
  (u957 : sort 0)
-> (u957
    -> u957)
-> Prelude.Integer
-> u957
-> u957
```

**Comment by robdockins** [comment]
It looks well-typed to me.  I think the problem is just expecting it to have `sort 0`.

**Comment by brianhuffman** [comment]
I believe that the primitive `fix` (which is used to translate recursive functions) just has a too-restrictive type: https://github.com/GaloisInc/saw-script/blob/03b0fa8d0c8b940a9604d5b9664a8370918018e4/saw-core/prelude/Prelude.sawcore#L19

I think the type error message is really complaining about the argument to `fix` having the wrong type (`sort 1` vs the expected `sort 0` for argument `a`). By the way, we should try to include more location information on such error messages so that I don't have to guess about things like that.

**Comment by brianhuffman** [comment]
Indeed, changing the type of `fix` to `(a : sort 1) -> (a -> a) -> a` fixes the problem:
```
sawscript> let {{ funpow f (n : Integer) x = if n <= 0 then x else funpow f (n - 1) (f x) }}
sawscript> check_term {{ funpow }}
[18:40:25.702] (u957 : sort 0)
-> (u957
    -> u957)
-> Prelude.Integer
-> u957
-> u957
```
