### ISSUE TITLE
Type is "incompatible" with its definition.

### ISSUE THREAD

**Issue by ntc2** [GaloisInc/saw-script#132]
The code is here: https://github.com/GaloisInc/saw-script/commit/1543e4026f515f7b46efabe14c6cd227a5278d38

Running `saw test.saw` produces:

    Loading module Cryptol
    Loading file "test.saw"
    Loading module Main
    Verifying 'inc_1' using 'llvm_verify':
    saw: user error (Incompatible type:
      Expected: TCon (TC TCSeq) [TCon (TC (TCNum 32)) [],TCon (TC TCBit) []]
        Got: Forall {sVars = [], sProps = [], sType = TUser (Name {nUnique = 194, nInfo = Declared "Main", nIdent = Ident False "Alg", nLoc = Range {from = Position {line = 1, col = 6}, to = Position {line = 1, col = 9}, source = "./test.cry"}}) [] (TCon (TC TCSeq) [TCon (TC (TCNum 32)) [],TCon (TC TCBit) []])}
          In context: llvm_assert_eq
          )

It's referring to this line in `test.saw`:

    llvm_assert_eq "st->0" {{ INC_1 }};

The problem goes away if you add a type annotation:

    llvm_assert_eq "st->0" {{ INC_1 : [32] }};

But this looks like a bug, since `test.cry` defines

    type Alg = [32]
    INC_1 = 0 : Alg

Indeed, the error message appears to be saying that the named type
`Alg`, which is definitionally equal to `[32]Bit`, is not compatible
with the type `[32]Bit`.

**Comment by brianhuffman** [comment]
Whenever we compare cryptol types for equality, we must compare using equivalence up to type synonyms. This is definitely a bug.

Also we should improve the type error message by using pretty-printed types, i.e. `[32]` instead of `TCon (TC TCSeq) [TCon (TC (TCNum 32)) [],TCon (TC TCBit) []]`.

**Comment by ntc2** [comment]
Yes, `[32]` is a little easier on the eyes ;)
