### ISSUE TITLE
Support for LLVM's insertelement and insertvalue

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#135]
I've compiled some C code w/ LLVM 3.2.6 using -O2, -O1.

If using `-O2` I get: 
`saw: user error (Unsupported instruction: insertelement <4 x i8> undef, i8 %2, i32 0)`

If using `-O1` I get:
`saw: user error (Unsupported instruction: insertvalue { i8*, i64 } undef, i8* %ptr, 0)`

It would be nice to support these instructions. Thanks!

**Comment by atomb** [comment]
These instructions are supported by the Crucible-based LLVM verification interface.

**Comment by atomb** [comment]
Now that the Crucible-based LLVM interface has been thoroughly used, we're planning to deprecate the original, LSS-based code. So I'm closing this with the `wontfix` label.
