### ISSUE TITLE
"index out of bounds" error shouldn't exit REPL

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#138]
For example:

```
sawscript> print {{ [True]@2 }}
saw: at: index out of bounds
```

The REPL then exits to the command prompt. It should instead return to the REPL prompt.

**Comment by brianhuffman** [comment]
Part of the problem is that some of our primitives have a single implementation that runs in a different monad depending on the backend (`Identity` for concrete evaluation, `IO` for SBV and ABC). If a primitive uses `fail` to report an error, this turns into an `IOException` in `IO`, but it turns into a call to `error` in `Identity` (which raises an asynchronous exception). This makes it more complicated to catch the errors in each case, since we can't use the same method for both.

**Comment by atomb** [comment]
Can we use some sort of error-tracking monad instead of `Identity` for concrete evaluation?

**Comment by eddywestbrook** [comment]
A simpler idea, that would require less change to the simulator(s), would be to have errors in the simulator throw a new type of `Exception`, maybe a `SimulatorException` or something like that. The idea would be that `error` should really be reserved for unrecoverable failures, but things that are recoverable at the REPL, like having an index that is too large, should use a different mechanism.

Thoughts?

**Comment by atomb** [comment]
I would take that one step farther and say that even totally unrecoverable things could use some custom exception so that we can give good error messages, even if we can't otherwise recover. Also, @kwf has been giving some thought to this topic, and I'd be interested in their input.

**Comment by atomb** [comment]
This specific case no longer causes the REPL to exit (and I think many other failures should be fixed along with that). I think #870 captures the remaining work to be done.
