### ISSUE TITLE
Confusing error message when applying record selector to function.

### ISSUE THREAD

**Issue by ntc2** [GaloisInc/saw-script#139]
E.g.
```
let f x = { val = x };
print f.val;
```
produces
```
We only support simple record lookup for now.
Please add type signature on argument.
```
The problem is that I forgot to give an argument to `f`, but the error message encourage me to try
```
print (f.val : Int)
```
which results in the same error message.

Perhaps something like
```
The record selector 'val' was applied to an incompatible term of type 'Int -> { val : Int}'
```
would be more helpful. And extra points for a line number.

**Comment by brianhuffman** [comment]
Revision a30cfcb changes the error message to something that makes more sense. Providing a line number would require much a bigger change, as we're not currently tracking location information in the parsed AST. @ntc2, you're welcome to add a separate ticket for location information on saw-script type error messages if you think that would be helpful.
