### ISSUE TITLE
`Bool` values aren't injected into Cryptol expressions 

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/saw-script#1404]
The SAW manual [claims](https://saw.galois.com/manual.html#cryptol-and-its-role-in-saw):

> * Any variable in scope that has SAWScript type `Bool` is visible in Cryptol expressions as a value of type `Bit`.

This doesn't appear to be true in practice, however:

```
$ ~/Software/saw-0.8/bin/saw 
 ┏━━━┓━━━┓━┓━┓━┓
 ┃ ━━┓ ╻ ┃ ┃ ┃ ┃
 ┣━━ ┃ ╻ ┃┓ ╻ ┏┛
 ┗━━━┛━┛━┛┗━┛━┛ version 0.8



sawscript> let b = true;
sawscript> {{ b }}

Cryptol error:
[error] at <stdin>:1:4--1:5 Value not in scope: b
```

**Comment by brianhuffman** [comment]
To implement this feature, we'll just need to add a new case for constructor `VBool` to function `extendEnv` in module `SAWScript.Value`:
https://github.com/GaloisInc/saw-script/blob/d3a887206cc38933c3d430eecfed176ddf2f98a4/src/SAWScript/Value.hs#L560-L584

**Comment by brianhuffman** [comment]
Adding this case should do it:
```
         VBool b ->
           do t <- scBool sc b
              let schema = Cryptol.tMono Cryptol.tBit
              let tt = TypedTerm (TypedTermSchema schema) t
              pure $ CEnv.bindTypedTerm (ident, tt) ce
```
