### ISSUE TITLE
Location information for run-time errors in saw-script

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#141]
When a saw-script command causes a run-time error, it would be useful for the error message to be able to report the location (line number) of the command that caused the error.

This could probably be implemented by saving the current line number in the `TopLevel` monad state, updating it after executing each statement in a statement block.

**Comment by ntc2** [comment]
Stack traces would be even better. I tried this a few weeks ago when I was blocked on something else on s2n, but I didn't get very far. I extended the `TopLevel` with stack state, but didn't get to extending the AST with more location information (I mostly tried some hacks that used the existing, partial location information, but didn't end up with anything good). I pushed the branch, in case someone wants to reuse the `TopLevel` enhancements: https://github.com/GaloisInc/saw-script/commit/d98154026ef13ad01e50a72e04cafc275f040ceb#diff-684abfa8e746c6855fb2d4e058e77c1cR361.

**Comment by robby-phd** [comment]
Recently, I got a "Bit conversion not supported" error that would be helpful if there is a location information to identify which program statement causing the issue.
Here's the specific example (take out the #ifndef SAW ... #endif to see the error):
https://github.com/GaloisInc/saw-script/blob/702b1b839d0f81293dce331a27b4a80506265f82/examples/simon-speck/speck.c#L114-L309

**Comment by brianhuffman** [comment]
The stack trace information is only printed for errors that are raised by a call to `fail` in the `IO` monad (or one of the monads built on top of `IO` such as `TopLevel`) which causes a `UserError` exception. If anyone discovers an error message from a saw-script primitive that does not come with a stack trace, then that means the error must have been raised in a different way; such cases should be filed as separate bugs.

Eventually, we should move away from using `fail`, and instead define our own custom exception type that we can throw instead.
