### ISSUE TITLE
Unable to build "out of the box" on OS X with ghc 8.0.1

### ISSUE THREAD

**Issue by dmzimmerman** [GaloisInc/saw-script#148]
When attempting to build saw-script on OS X with ghc 8.0.1 (installed from Homebrew), I symlink `stack.ghc-8.0-unix.yaml` to `stack.yaml`, run `./build_sandbox.sh`, and after a while get the following:

```
No packages found in snapshot which provide a "hsc2hs" executable, which is a build-tool dependency of "terminal-size"
Missing build-tools may be caused by dependencies of the build-tool being overridden by extra-deps.
This should be fixed soon - see this issue https://github.com/commercialhaskell/stack/issues/595

While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      jvm-parser: needed (>=0.3), 0.2.1.9 found
    needed for package jvm-verifier-0.4

--  Failure when adding dependencies:    
      jvm-verifier: needed (-any), couldn't resolve its dependencies
    needed for package saw-script-0.2
```

Two issues are interesting here: first the `hsc2hs` executable is in fact available on my system, so I don't see why it's complaining about that; and second, the 0.3 version of `jvm-parser` is only available in the `java8` branch, which is not the branch that is grabbed as a dependency by `get-dependencies.sh`. Manually switching `jvm-parser`  in the `deps` directory to the `java8` branch after `get-dependencies.sh` has run allows saw-script to build.

**Comment by atomb** [comment]
This should be fixed now. The `java8` branch of `jvm-parser` has been merged into `master`.

I think the message about `hsc2hs` is spurious, and the `jvm-parser` version issue is really what's causing the build to fail above.
