### ISSUE TITLE
Proving using rme gives an unimplemented error message

### ISSUE THREAD

**Issue by robby-phd** [GaloisInc/saw-script#151]
Error message: `Unimplemented global: Prelude.bvSShr`.

**Comment by robdockins** [comment]
Indeed, it seems this primitive is missing. See:

https://github.com/GaloisInc/saw-core/blob/master/src/Verifier/SAW/Simulator/RME.hs#L250

I think it just got overlooked.

**Comment by robdockins** [comment]
This should be fixed by GaloisInc/saw-core@fba99a582cd1734ce045b6d8b2a9cd7515cea00e
