### ISSUE TITLE
Make the Crucible backend parametric in the SMT solver

### ISSUE THREAD

**Issue by andreistefanescu** [GaloisInc/saw-script#1520]
https://github.com/GaloisInc/saw-script/pull/1515 switches the SMT solver used during the Crucible symbolic execution from Yices to Z3: https://github.com/GaloisInc/saw-script/blob/608c65e46db93da7582b0b31107d4820aee61ed8/src/SAWScript/Crucible/Common.hs#L43
Let's make the Crucible backend parametric in the SMT solver. This it not as easy as it could be because the SMT solver choice is part of the type of the backend.

**Comment by robdockins** [comment]
Fixed via #1672. The new (experimental) `set_path_sat_solver` command allows users to select which solver to use for path-sat checking.  Currently only Z3 and Yices are supported, but it would be relatively easy to add others.
