### ISSUE TITLE
Reference manual for built-in primitives

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/saw-script#153]
Right now, you can get a list of primitives/built-in functions/etc. by typing `env`.

Then you can type `:?` on one of those to get the help for it.

But to get the help on all of them at once (so you can search), you either need to search the source or write a script to do the above for all entries. (I've done the latter, and it's quite handy.)

Please add a pre-built manual with this information. This will greatly assist in user "discovery" of features.

**Comment by atomb** [comment]
There's now a manual in the `doc/manual` directory which describes almost all of the built-in functions.
