### ISSUE TITLE
SAW fails on irrelevant unsupported instructions

### ISSUE THREAD

**Issue by ntc2** [GaloisInc/saw-script#154]
C code in `test.c`:

``` c
int f() {
  return 1;
}

int g(double x) {
  return x == 0.0;
}
```

SAW script in `test.saw`:

```
m <- llvm_load_module "test.bc";

let f_spec = do {
  llvm_return {{ 1 : [32] }};
  llvm_verify_tactic yices;
};

llvm_verify m "f" [] f_spec;
```

Output:

``` console
$ saw test.saw
Loading module Cryptol
Loading file "/var/tmp/saw-bug-floating-point/test.saw"
saw: user error ("llvm_verify" (/var/tmp/saw-bug-floating-point/test.saw:8:1):
Unsupported instruction: fcmp oeq double %2, 0.0)
```

Of course, the floating point code is part of the irrelevant function `g`, and if I comment out `g`'s definition in `test.c` and rebuild `test.bc` everything works. I'm using Clang 3.6.

Perhaps SAW could simply generate a warning when loading unsupported instructions, and only fail later if they actually need to be simulated?

Source attached (zip bomb / no top-level directory): [test.zip](https://github.com/GaloisInc/saw-script/files/340523/test.zip)

**Comment by TomMD** [comment]
This title is a bit misleading, the instructions are only irrelevant in your case.  I recently had a similar case which reported `Not Yet Implemented: FpToUi`.  Even some really basic floating point support could be significant wrt usability.

**Comment by atomb** [comment]
I think #7 gives a better description of the problem and solution, and this issue is no longer necessary.
