### ISSUE TITLE
Cryptol comparisons don't translate nicely into saw-core

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#1565]
When you translate a Cryptol term using the `<$` operator into SAW, you currently get an unnecessarily complicated term:
```
sawscript> rewrite (cryptol_ss ()) {{ \(x : [8]) y -> x <$ y }}
let { x@1 = Prelude.Vec 8 Prelude.Bool
    }
 in \(x : x@1) ->
      \(y : x@1) ->
        Prelude.or (Prelude.bvslt 8 x y)
          (Prelude.and (Prelude.bvEq 8 x y) Prelude.False)
```

The `or _ (and (bvEq x y) False)` part is completely redundant. We should translate this simply as `bvslt`.

**Comment by brianhuffman** [comment]
Turns out this is not specific to signed comparisons. Ordinary `<` and `<=` do the same thing:
```
sawscript> rewrite (cryptol_ss()) {{ \(x:[8]) (y:[8]) -> x < y }}
let { x@1 = Prelude.Vec 8 Prelude.Bool
    }
 in \(x : x@1) ->
      \(y : x@1) ->
        Prelude.or (Prelude.bvult 8 x y)
          (Prelude.and (Prelude.bvEq 8 x y) Prelude.False)
sawscript> rewrite (cryptol_ss()) {{ \(x:[8]) (y:[8]) -> x <= y }}
let { x@1 = Prelude.Vec 8 Prelude.Bool
    }
 in \(x : x@1) ->
      \(y : x@1) ->
        Prelude.not
          (Prelude.or (Prelude.bvult 8 y x)
             (Prelude.and (Prelude.bvEq 8 y x) Prelude.False))
```

**Comment by brianhuffman** [comment]
The problem comes from the way the `Cmp` and `SignedCmp` class dictionaries are defined in `Cryptol.sawcore`.
https://github.com/GaloisInc/saw-script/blob/db538d30a650f9e89eb9410fcb58bc2f411f9a26/cryptol-saw-core/saw/Cryptol.sawcore#L537-L541
https://github.com/GaloisInc/saw-script/blob/db538d30a650f9e89eb9410fcb58bc2f411f9a26/cryptol-saw-core/saw/Cryptol.sawcore#L583-L587

Instead of only a single continuation-style all-purpose comparison operator, the class dictionary also needs ordinary comparison operators that can be defined without extra `and`s and `or`s.

**Comment by robdockins** [comment]
Does the standard simpset not include boolean identities that would collapse this?

**Comment by brianhuffman** [comment]
I remember implementing that dictionary passing translation. There was a specific reason for using the `cmp` field of type `a -> a -> Bool -> Bool` for comparisons: I wanted something that would correctly implement lexicographic ordering for compound types without being stupidly inefficient. Normally on type `(a, b)` you'd define `(u, v) < (x, y)` as `(u < x) \/ (u == x /\ v < y)`. But if type `a` is itself a complex type, then you don't want to have to traverse `u` and `x` twice to compute the comparison result. The `cmp` approach works well in that regard. But what I failed to do is add special cases to simplify the comparison formulas for basic types.

**Comment by robdockins** [comment]
Maybe we could change the type of `cmp` to something like `cmp : a -> a -> Maybe Bool -> Bool`, where a `Nothing` indicates that there's no interesting continuation and to just emit the basic less than test.

**Comment by brianhuffman** [comment]
Yeah, I thought about using a `Maybe` type, but we also don't want to leave any recursors for the `Maybe` type lying around in the resulting term either. I think what we should do is just add a `gt` field to the `Cmp` dictionary that just implements the plain greater-than comparison. The `Cmp` dictionary constructors for compound types like `(a, b)` would define `gt` on the pair type in terms of `cmp` on type `a` and `gt` on type `b`.
