### ISSUE TITLE
Enhance `trivial` proof tactic

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#1567]
Currently the `trivial` proof tactic can only discharge proof states with goals of the form `EqTrue True` (possibly surrounded by some number of Pi quantifiers). It would be good to generalize this a bit. In particular, we should enable it to solve any goal of the form `Eq t x x` by reflexivity. Note that `EqTrue True` is definitionally equal to `Eq Bit True True`, so it is also an instance of reflexivity.

Even better would be to have an extensible set of theorems that could be resolved with proof goals to solve them, of which reflexivity could be one.

**Comment by brianhuffman** [comment]
Yeah, maybe the extensibility is a bit overkill for `trivial`. (The idea was inspired by the `.` tactic in Isabelle/Isar proofs, which is similarly extensible.) I like the reflexivity-up-to-conversion idea.

**Comment by robdockins** [comment]
Does `scConvertible` do the job we want?

**Comment by brianhuffman** [comment]
Not quite. We really want to check whether a term unifies with the pattern `Eq ?t ?x ?x` modulo convertibility, but `scConvertible` requires two complete terms, not a term and a pattern.

Unless we want to implement a generic matching- or unification-modulo-convertibility operation, we might need to do something a bit ad-hoc. Probably what we need is to evaluate the goal to whnf (with `scWhnf`), then check that it's of the form `Eq ?t ?x ?y`, and finally call `scConvertible` on the terms that matched `?x` and `?y`.

**Comment by robdockins** [comment]
Your second paragraph there was basically what I had in mind, modulo questions about handling free variables from going under Pi binders.

**Comment by robdockins** [comment]
I guess we could just try to actually build the corresponding proof term and type-check it? That might be easier.

**Comment by robdockins** [comment]
Some local testing indicates that building a candidate proof term from `Refl` and checking that it is convertible with the goal will work.  I think this should be pretty easy to implement.

**Comment by robdockins** [comment]
Fixed via #1568
