### ISSUE TITLE
Allow reading and writing structured objects in LLVM analysis

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#159]
Right now, arrays of scalars can be read and written from the LLVM heap as monolithic entities. Similarly, it would be possible in principle to specify or extract the value of a struct or a nested array as a SAWCore tuple or nested vector, but that's not currently implemented.

**Comment by brianhuffman** [comment]
This was indeed already implemented. With the addition of an integration test that uses the feature (#1015) I think we can close the ticket.
