### ISSUE TITLE
Avoid use of `git://` URLs in submodules

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/saw-script#1620]
GitHub recently [removed support for `git://` URLs](https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git). Unfortunately, this causes problems for SAW, at least one submodule makes use of a `git://` URL. See this [failing CI job](https://github.com/GaloisInc/saw-script/runs/5591067116?check_suite_focus=true) for an example:

```
Submodule 'blst' (https://github.com/supranational/blst) registered for path 'blst'
Submodule 'cryptol-specs' (git://github.com/GaloisInc/cryptol-specs) registered for path 'cryptol-specs'
Cloning into '/workdir/blst'...
Cloning into '/workdir/cryptol-specs'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
fatal: clone of 'git://github.com/GaloisInc/cryptol-specs' into submodule path '/workdir/cryptol-specs' failed
```

This arises from [this line](https://github.com/GaloisInc/BLST-Verification/blob/05d29b0e9d826053185e5bdba287045aab0b4669/.gitmodules#L6) in the `blst-verification` repo. It's possible that there are others, too, since `heapster.saw` resorts to this trick:

https://github.com/GaloisInc/saw-script/blob/09463dd8dc3762c38ae0606c719619879421f894/heapster.dockerfile#L37-L39

Now that `git://` is officially no longer supported, we should:

1. Patch all affected submodules upstream to remove their use of `git://` URLs,
2. Update the commits in `saw-script`'s Dockerfiles accordingly, and
3. Remove any uses of `git config --global url."https://".insteadOf git://` in the Dockerfiles to ensure that everything works as expected.

**Comment by sauclovian-g** [comment]
There are no such URLs left these days.

**Comment by sauclovian-g** [comment]
That was a little optimistic; there's still an insteadOf. Also, there's a stray reference in one of macaw's cabal files that probably doesn't affect us but should get fixed in macaw.
