### ISSUE TITLE
Non-exhaustive pattern matches in heapster-saw

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#1632]
We should fix this warning:
```
heapster-saw       > [ 6 of 19] Compiling Verifier.SAW.Heapster.Permissions
heapster-saw       >
heapster-saw       > /Users/huffman/Work/saw-script/heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs:4810:5: warning: [-Wincomplete-patterns]
heapster-saw       >     Pattern match(es) are non-exhaustive
heapster-saw       >     In an equation for ‘go’:
heapster-saw       >         Patterns not matched:
heapster-saw       >             (PExpr_Var _) []
heapster-saw       >             (PExpr_Var _) (_:_)
heapster-saw       >             (PExpr_BV _ _) []
heapster-saw       >             (PExpr_BV _ _) (_:_)
heapster-saw       >      |
heapster-saw       > 4810 |     go off borrows
heapster-saw       >      |     ^^^^^^^^^^^^^^...
```
https://github.com/GaloisInc/saw-script/blob/2b0b46b4a5a2e18cde76a96c5bee15bf1641f5db/heapster-saw/src/Verifier/SAW/Heapster/Permissions.hs#L4810-L4814

For any "impossible" cases, we should add calls to `panic`. I also see that the same file contains many uses of the `error` function; those should be replaced by `panic` as appropriate.

**Comment by eddywestbrook** [comment]
Yes, I have noticed this non-exhaustive case as well, and have fixed it in the branch I am currently working on. I can change the `error` calls to `panic` in a later change, after this one that I'm currently working on.

**Comment by RyanGlScott** [comment]
This warning appears to have been fixed in the `master` branch.
