### ISSUE TITLE
Latest what4 version causes cabal configuration failure

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#1635]
Updating the `what4` submodule to include GaloisInc/what4#198 causes the following error in saw-script when you try to run `cabal configure --enable-tests` or `cabal build --enable-tests`:
```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: parameterized-utils-2.1.5.0.99 (user goal)
[__1] rejecting: parameterized-utils:!test (constraint from config file,
command line flag, or user target requires opposite flag selection)
[__1] trying: parameterized-utils:*test
[__2] trying: tasty-hedgehog-1.1.0.0 (dependency of parameterized-utils *test)
[__3] trying: what4-1.2.1.0.99 (user goal)
[__4] rejecting: what4:!test (constraint from config file, command line flag,
or user target requires opposite flag selection)
[__4] rejecting: what4:*test (conflict: tasty-hedgehog==1.1.0.0, what4 *test
=> tasty-hedgehog>=1.2)
[__4] fail (backjumping, conflict set: tasty-hedgehog, what4, what4:test)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: parameterized-utils, tasty-hedgehog,
what4, parameterized-utils:test, what4:test
Try running with --minimize-conflict-set to improve the error message.
```

**Comment by brianhuffman** [comment]
Updating the `parameterized-utils` submodule to include GaloisInc/parameterized-utils#131 causes the same error. It looks like it's an issue with a `tasty-hedgehog` version constraint.

**Comment by RyanGlScott** [comment]
Indeed, both https://github.com/GaloisInc/parameterized-utils/pull/131 and https://github.com/GaloisInc/what4/pull/198 bump the lower version bounds on `tasty-hedgehog` to `>= 1.2`. Does the configuration error still happen if you bump both submodules simultaneously?

**Comment by brianhuffman** [comment]
Yes, it does. But it looks like it works if I regenerate all the freeze files first; the freeze files had all specified an earlier version of `tasty-hedgehog`. I'll include the regenerated freeze files in the latest bump-submodules PR (#1634).
