### ISSUE TITLE
Feature Request: allow `for` looping over Cryptol lists

### ISSUE THREAD

**Issue by ntc2** [GaloisInc/saw-script#164]
What I'm asking for, which does not work:

```
let xs = {{ [1,2 :[32]] }};
for xs (\x -> llvm_assert {{ x > 0 }});
```

Workarounds that currently work:

```
let xs = [1,2];
for xs (\x -> llvm_assert {{ (`x : [32]) > 0 }});
```

and

```
let xs = [{{1:[32]}},{{2:[32]}}];
for xs (\x -> llvm_assert {{ x > 0 }});
```

A related problem is that the error message in the first case is not
very helpful:

```
saw: user error (type mismatch: Term -> t.49 and [t.51] -> (t.51 -> t.50 t.52) -> t.50 [t.52]
 at "decode_inverts_encode_spec" (verify.saw:3:5)
mismatched type constructors: Term and ([])

)
```

(also/ongoing, the line number is for the first line of the function
containing the error, not the line within that function the error
itself).

**Comment by brianhuffman** [comment]
The easiest way to fix this will be to add a new saw-script primitive `eval_list` of type `Term -> [Term]`, which would yield a list of terms corresponding to the elements of the given term, which should have an array type. (C.f. the existing constants `eval_bool`, `eval_int`.) Then you'd be able to write
```
let xs = {{ [1,2 :[32]] }};
for (eval_list xs) (\x -> llvm_assert {{ x > 0 }});
```
