### ISSUE TITLE
abc doesn't work with saw-remote-api container

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#1647]
My guess is that this is because `abc` is built in `what4-solvers` to rely on some shared libraries such as libreadline, but which are not present in the `saw-remote-api` container. Since the binaries are copied from the `what4-solvers` release into the `saw-remote-api` container, `abc` can't find those shared libraries.

https://github.com/GaloisInc/saw-script/blob/master/saw-remote-api/Dockerfile

**Comment by RyanGlScott** [comment]
Good catch. I think adding `libreadline-dev` to the list of packages installed in `saw-remote-api`'s `Dockerfile` should fix this issue, similarly to how it's done in [`saw`'s `Dockerfile`](https://github.com/GaloisInc/saw-script/commit/8e716b72ccb74db23f01aa386beb667d095ae70a).

**Comment by weaversa** [comment]
Perfect! Thank you!

**Comment by RyanGlScott** [comment]
Fixed in #1652.
