### ISSUE TITLE
Feature Request: symbolic simulation profiling

### ISSUE THREAD

**Issue by ntc2** [GaloisInc/saw-script#165]
It would be useful to get a timing profile for symbolic simulation: a list of (e.g. LLVM) function names followed by the cumulative (including sub calls) and non cumulative run time. Sorting the results by cumulative time might be a good default. To get other sort orders, we can pipe the output into `sort -k <i>,<i>n` or whatever.

The best approximation I have right now is running `saw -v2` and paying attention to which function names stay on the screen for a long time.

**Comment by siddharthist** [comment]
@robdockins @lukemaurer [There appears to be some support in Crucible for profiling](https://github.com/GaloisInc/crucible/blob/8a6299b4c80d42e3ca57b61335e25df29a6b9f48/crucible/src/Lang/Crucible/Simulator/Profiling.hs), can you comment on the status of this issue?

**Comment by atomb** [comment]
There's pretty comprehensive support in Crucible, and I think what remains for this issue is mostly a matter of adding the UI to enable it.

**Comment by robdockins** [comment]
Indeed, it's really just a question of how to expose that functionality to the SAW user.

**Comment by siddharthist** [comment]
Looks like this and #364 are duplicates.
