### ISSUE TITLE
Problem with running tutorial examples on Mac

### ISSUE THREAD

**Issue by ctchou** [GaloisInc/saw-script#167]
I downloaded the binary release of SAW for Mac:

saw-0.2-2016-04-12-MacOSX-64

and am trying to work through the examples in the tutorial.  I compiled ffs.c to LLVM exactly as specified in the tutorial:

# clang -c -emit-llvm -o ffs.bc ffs.c

But when I tried to run the first SAW script, I encountered the following error:

# saw ffs_llvm.saw
Loading module Cryptol
Loading file "ffs_llvm.saw"
Extracting reference term: ffs_ref
saw: user error (Bitcode parsing of ffs.bc failed:
match failed)

However, the SAW script works fine with the LLVM bitcode shipped with the release.  Is there anything special I need to do when using Mac's clang?  The clang I'm using is:

# clang --version
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Many thanks in advance!

**Comment by TomMD** [comment]
YES!  There is an issue with never versions of LLVM bitcode.  IIRC, llvm 3.6 should work.

This is a well known issue, sorry you ran into it.  We certainly have plans to fix things up, the lack of a firm specification and versioning for LLVM BC complicates things a tad (expect there to be a lag between release of new formats and saw support) but a path forward is conceptually decided on.

CC @elliottt

**Comment by ctchou** [comment]
I downloaded LLVM 3.6.2 and its clang works with SAW.  Thanks!

Perhaps you guys should put a note in the tutorial or the website regarding this issue.
