### ISSUE TITLE
Python: Undeprecate `proclaim`

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/saw-script#1676]
#1644 adds support for `llvm_assert`, which behaves like `llvm_precondition` or `llvm_postcondition` depending on where it is used in a specification. We would like to have a Python counterpart to `llvm_assert`, and in fact, we already have one in the form of the [`proclaim`](https://github.com/GaloisInc/saw-script/blob/f7a0de183cf6d23182e2a236bc251074bd13cff4/saw-remote-api/python/saw_client/crucible.py#L496) function. `proclaim` is currently marked as deprecated, but given that we want to support something like it going forward, it makes sense to remove the deprecation warning and allow users to call it without warnings.

**Comment by smithnormform** [comment]
It might also be nice to have a `proclaim_f` function like `precondition_f` and `postcondition_f`.
