### ISSUE TITLE
llvm symbolic simulator should assume address of stack-allocated var is non-NULL

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#173]
Here's a minimized example. First, `example.c`:
```
#include <stdlib.h>
int is_null (int *x) {
    if (x == NULL) return 1;
    else return 0;
}
int foo () {
    int x = 5;
    return is_null(&x);
}
```
Compile this to `example.bc`, and then run this in saw-script:
```
m <- llvm_load_module "example.bc";
llvm_verify m "foo" []
  do {
    llvm_return {{ 0:[32] }};
    llvm_verify_tactic z3;
  };
```
I would expect the `llvm_verify` to succeed, since any stack-allocated variable should have a non-NULL address. But the result:
```
When verifying @foo:
Proof of return value failed.
Counterexample:
  lss__alloc0: 0
return value
Encountered:  1
Expected:     0
```

**Comment by atomb** [comment]
I looked into trying to fix this within the LSS code base, and it seems like it would be quite complex. I'd say that this is one of the many reasons to migrate to the Crucible-based LLVM infrastructure.

**Comment by atomb** [comment]
And I can confirm that this works with `crucible_llvm_verify`.

**Comment by brianhuffman** [comment]
Closing and labeling as "won't fix".
