### ISSUE TITLE
saw-script needs a way to specify arrays of pointers in LLVMSetup blocks

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#176]
The `llvm_array` function expects the element type to be given as a `LLVMType` value. However, no function is provided for creating an `LLVMType` for pointers.

A related problem is that the `llvm_ptr` command can only specify pointers that are accessible via a sequence of pointer dereferences and struct member lookups; we can't express array indexing.

**Comment by atomb** [comment]
We now have a way to do this with Crucible. It doesn't work with LSS.
