### ISSUE TITLE
`saw-core`: Duplicate axioms `bvNat_bvToNat` and `bvNat_bvToNat_id`

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/saw-script#1785]
Currently, `Prelude.sawcore` contains these axioms:

https://github.com/GaloisInc/saw-script/blob/8f7253285c4a486c13cc89d212387be093d2ed66/saw-core/prelude/Prelude.sawcore#L3156-L3160
https://github.com/GaloisInc/saw-script/blob/8f7253285c4a486c13cc89d212387be093d2ed66/saw-core/prelude/Prelude.sawcore#L1221-L1222

As far as I can tell, these axioms are duplicates. Since `bvNat_bvToNat` was added before `bvNat_bvToNat_id`, I propose removing the latter in favor of the former.

**Comment by eddywestbrook** [comment]
Agreed, these do seem like duplicates, and it does make sense to remove the most recently added
