### ISSUE TITLE
saw-remote-api python client install needs ../../deps/cryptol/cryptol-remote-api/python

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#1818]
```
$ wget https://github.com/GaloisInc/saw-script/archive/refs/heads/master.zip && unzip master.zip
$ cd saw-script-master/saw-remote-api/python
$ poetry install
```

This complains about not being able to find `../../deps/cryptol/cryptol-remote-api/python`, which is a new error, and kind of strange.

If I do go grab cryptol and stick it in `../../deps`, the install goes fine. It's worth noting that this error happens even if I have already installed the `cryptol-remote-api` python client.

**Comment by RyanGlScott** [comment]
The key line in question is here:

https://github.com/GaloisInc/saw-script/blob/9acd534ab65dcc38132675bb412db63a41745932/saw-remote-api/python/pyproject.toml#L17

We are depending on a development version of `cryptol-remote-api` that is not yet released on PyPI. This is by design, as the `cryptol` submodule commit we are depending on is also a development version. As such, you will need to have `cryptol` checked out as a submodule (or, as you've done, placed it under `deps`).

**Comment by RyanGlScott** [comment]
Does https://github.com/GaloisInc/saw-script/issues/1818#issuecomment-1424831305 resolve this issue for you, @weaversa?

**Comment by weaversa** [comment]
> Does [#1818 (comment)](https://github.com/GaloisInc/saw-script/issues/1818#issuecomment-1424831305) resolve this issue for you, @weaversa?

I can install the python client, but it's awkward. I'm putting the client in a Dockerfile, and rather than `git clone` the repo, I am downloading the master.zip. The zip file doesn't have a `deps` folder, so I have to create one and then manually grab the cryptol master.zip and unzip it to the correct spot. I also delete everything except the python folders (I'm trying to keep the layers small).

Ideally, it would be nice if I could `pip install saw-client` (or something) and know that I'm getting a recent working version that is synced w/ a same `pip install cryptol-client` as well as `apt-get install` recent versions of Cryptol and SAW. I realize I could use the pip versions, but so many new features are added to Cryptol and SAW all the time, and the release schedule is not regular (the last release for SAW was Oct 7, 2021, 1360 commits ago), so I'm forced to use the nightlies for everything we do. It might be a lot to ask, but it would be nice to have shorter scheduled releases (monthly?) for Cryptol and SAW (even if only the minor version number changes).

**Comment by RyanGlScott** [comment]
As of commit 550e66e7a21a73435e513c4a3193afac2701eb7e, we now depend on the `cryptol-3.0.0` release from PyPI, so we are no longer vendoring in a copy of the Python `cryptol` bindings from GitHub.
