### ISSUE TITLE
Heapster tutorial's build instructions are broken

### ISSUE THREAD

**Issue by scuellar** [GaloisInc/saw-script#1822]
Probably after commit [d2d9f01ce960209838f02af27a75d2d628e4094b](https://github.com/GaloisInc/saw-script/commit/d2d9f01ce960209838f02af27a75d2d628e4094b) the heapster build needs more specific instructions on building coq.

Specifically, it requires a particular version of EnTree.

**Comment by RyanGlScott** [comment]
My bad, I forgot to update the tutorial when writing #1778. It should just be a matter of this part of the `saw-core-coq` README:

https://github.com/GaloisInc/saw-script/blob/9acd534ab65dcc38132675bb412db63a41745932/saw-core-coq/README.md?plain=1#L24-L35

**Comment by scuellar** [comment]
Actually, I now realized the tutorial is fine. It points to that README correctly, I just had the wrong version of 'entree-specs'. 

I'm closing this issue.
