### ISSUE TITLE
crucible_llvm_verify should print counterexamples from failed proofs

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#188]
Currently, if a proof script on a `crucible_llvm_verify` command fails, it just prints `Proof failed!` and the name of the function being verified.

Instead, it should print a full counterexample (if the proof script produces one) using the variable names from the `crucible_fresh_var` setup statements. The older `llvm_verify` and `java_verify` commands already do this.

**Comment by atomb** [comment]
This is implemented now.
