### ISSUE TITLE
Errors during submodule fetch: 	deps/crucible

### ISSUE THREAD

**Issue by ramsdell** [GaloisInc/saw-script#1883]
I pulled the master branch right now and received an error saying something went wrong during a submodule fetch.  I think this is the nub of the problem.

```
fatal: remote error: upload-pack: not our ref 255b081de6757761592f8cdbb4f2804d88c7fb5a
Errors during submodule fetch:
	deps/crucible
```

[submoderr.txt](https://github.com/GaloisInc/saw-script/files/11887006/submoderr.txt)

**Comment by RyanGlScott** [comment]
This is unusual, as I'm not able to reproduce this locally. Does the issue persist if you run `git pull` on a subsequent attempt? Also, do you experience the error upon a fresh `saw-script` checkout?

**Comment by ramsdell** [comment]
I had no problems with a fresh checkout.  It must have been a transient error.
