### ISSUE TITLE
Crucible-based proof of Salsa20 fails when using overrides

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#189]
The Salsa20 code in `examples/salsa20` verifies with LSS with both monolithic and compositional approaches, and verifies with Crucible in both ways with one exception: the top-level `s20_crypt32` function works only without overrides.

Uncomment the `s20_crypt32` line in `salsa-crucible.saw` to see the problem. Comment out the `s20e32` override parameter to see it work correctly without overrides.

**Comment by atomb** [comment]
This turns out to be a question of passing uninitialized values across abstraction boundaries. The `keystream` local variable in `s20_crypt32` is passed in to `s20_expand32` as an output parameter. In monolithic execution, it only ever gets stored to. In compositional execution, the override over-zealously tries to read the initial value of that parameter (which does not yet exist) in case the specification _might_ need to make use of it.

Can we change the override mechanism so that it doesn't read the value specified by a `crucible_points_to` unless that value is actually needed? In particular, the `ks` value in `salsa20_expansion_32` in `salsa-crucible.saw` is never used.

This can be fixed by changing the C code, too. By changing

~~~~
uint8_t keystream[64];
~~~~

to

~~~~
uint8_t keystream[64] = { 0 };
~~~~

we can make it go through.

**Comment by brianhuffman** [comment]
There is no problem with saw-script here. The spec just needed to be modified not to use `crucible_points_to` in the precondition section.
