### ISSUE TITLE
Add Crucible LLVM override for __memset_chk

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#190]
The LSS-based simulator for LLVM has an override for the standard `__memset_chk` function, but this doesn't yet exist in Crucible. We should add it.

**Comment by brianhuffman** [comment]
Revision GaloisInc/crucible@d964688f added an override for `__memcpy_chk`. An override for `__memset_chk` could be done in the same way.

**Comment by brianhuffman** [comment]
Fixed in GaloisInc/crucible@f3f176b8743224b2a71fed0201f1d0f7d993766f.
