### ISSUE TITLE
[CI] Coq release download broken?

### ISSUE THREAD

**Issue by m-yac** [GaloisInc/saw-script#1909]
Just noticed that it looks like the way we're installing Coq on CI for the `heapster-tests` is broken. The command `opam repo add coq-released https://coq.inria.fr/opam/released` seems to be consistently giving the error:
```
[ERROR] Could not update repository "coq-released": OpamDownload.Download_fail(_, "Curl failed: \"/usr/bin/curl --write-out %{http_code}\\\\n --retry 3 --retry-delay 2 --user-agent opam/2.1.5 -L -o /tmp/opam-3475-f7f9de/index.tar.gz.part -- [https://coq.inria.fr/opam/released/index.tar.gz\](https://coq.inria.fr/opam/released/index.tar.gz/)" exited with code 28")
[ERROR] Initial repository fetch failed
'opam repo add coq-released https://coq.inria.fr/opam/released' failed.
Error: Process completed with exit code 40.
```

For example, here's the failure from a scheduled CI run on `master`: https://github.com/GaloisInc/saw-script/actions/runs/5854373290/job/15871358448#step:7:23

**Comment by RyanGlScott** [comment]
I suspect this is a server-side thing, as https://downforeveryoneorjustme.com/coq.inria.fr?proto=https suggests that https://coq.inria.fr is down (temporarily, I hope).

**Comment by m-yac** [comment]
Ah, yes. Checked the Coq mailing list and it looks like the server is just down: https://sympa.inria.fr/sympa/arc/coq-club/2023-08/msg00013.html

Apparently there are some holidays in France at the moment, so this might not get fixed for a few days. From this discussion on Zulip, it seems like other folks are just deciding to live with their CI being messed up for a couple days: https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Website.20down.3F

**Comment by eddywestbrook** [comment]
Funny, I saw the email thread go by on the Coq list about the Coq server being down, and I thought to myself "I'm glad this doesn't affect me." Silly me.

**Comment by m-yac** [comment]
This appears to be fixed: https://github.com/GaloisInc/saw-script/actions/runs/5881529261/job/15951471166?pr=1907
