### ISSUE TITLE
Suspicious code in `LLVM.ResolveSetupValue.resolveSAWPred`

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/saw-script#1910]
During a code review, @eddywestbrook noticed this part of `SAWScript.Crucible.LLVM.ResolveSetupValue.resolveSAWPred`:

https://github.com/GaloisInc/saw-script/blob/e0e94c6044e832081e28af8e9bdbf9a130caca48/src/SAWScript/Crucible/LLVM/ResolveSetupValue.hs#L734-L740

We make an effort to rewrite `tm` into `tm'`, but immediately afterwards we call `evalSharedTerm` on `tm`, not `tm'`. This seems very suspicious. I don't have a test case on hand to verify that this would introduce bugs, but I bet you could construct one with enough cleverness.

**Comment by eddywestbrook** [comment]
@andreistefanescu Do you have any insight here? I haven't done enough complex SAW proofs to generate a useful test case for this potential change.

**Comment by andreistefanescu** [comment]
this is the definition of `basic_ss`

https://github.com/GaloisInc/saw-script/blob/e0e94c6044e832081e28af8e9bdbf9a130caca48/src/SAWScript/Prover/Rewrite.hs#L21-L68

Those simplifications can eliminate variables, such as `true || x + 1 == x` rewrites to `true`. I don't know if `Concrete.evalSharedTerm` handles that via laziness. Either way, I don't see any reason not to switch to `tm'`. If we do that, let's make the change for JVM and MIR as well.

**Comment by RyanGlScott** [comment]
> If we do that, let's make the change for JVM and MIR as well.

FWIW, this code doesn't exist in the JVM backend, since it doesn't do any of this `evalSharedTerm` business for whatever reason. (Perhaps it should.)

**Comment by RyanGlScott** [comment]
Fixed in https://github.com/GaloisInc/saw-script/issues/2037.
