### ISSUE TITLE
Missing `LICENSE` in `verif-viewer` package

### ISSUE THREAD

**Issue by qsctr** [GaloisInc/saw-script#1917]
`verif-viewer/verif-viewer.cabal` lists `License-file: LICENSE` but the `LICENSE` file does not actually exist. This prevents running `cabal install` in the top-level directory to install SAW:
```
saw-script$ cabal install
Wrote tarball sdist to
saw-script/dist-newstyle/sdist/saw-script-1.0.0.99.tar.gz
Wrote tarball sdist to
saw-script/dist-newstyle/sdist/saw-remote-api-1.0.0.tar.gz
Wrote tarball sdist to
saw-script/dist-newstyle/sdist/crucible-mir-comp-0.1.tar.gz
Wrote tarball sdist to
saw-script/dist-newstyle/sdist/crux-mir-comp-0.4.tar.gz
Wrote tarball sdist to
saw-script/dist-newstyle/sdist/cryptol-saw-core-0.1.tar.gz
Wrote tarball sdist to
saw-script/dist-newstyle/sdist/rme-0.1.tar.gz
saw-script/verif-viewer/LICENSE: openBinaryFile: does not exist (No such file or directory)
```

**Comment by RyanGlScott** [comment]
Given that `verif-viewer.cabal` indicates that it is BSD-3–licensed, I think it would suffice to copy one of the other BSD-3 licenses elsewhere in the repo (e.g., [this one](https://github.com/GaloisInc/saw-script/blob/a618ae20d3682140a54e3c44710740b4a49e85e7/LICENSE)) over to `verif-viewer`.
