### ISSUE TITLE
crucible_fresh_pointer doesn't work with non-memtypes

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#193]
If I want to make a fresh pointer of type `void*` or `opaque*`, I might try to write
```
p <- crucible_fresh_pointer (llvm_type "opaque");
```
but this fails with the message `unsupported type: opaque`.

The failure is because saw tries to convert the given type to a `MemType` (as opposed to a `SymType`). Since we never need to allocate fresh pointers, we should be able to accept a `SymType` in this situation.

**Comment by atomb** [comment]
In addition to `void*` and `opaque*` types, it would be useful to be able to create fresh function pointers.
