### ISSUE TITLE
Add `crucible_no_simulate` to the Crucible backend

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/saw-script#201]
N.B. Related code is inline below.

The crucible backed does not properly allow overrides for undefined functions.  If `f` calls `g` but we only know the declaration of `g` (e.g.`extern int g(int)`) we need a method to obtain a methodspec that does not  involve simulation.  With the old backend that method was `llvm_no_simulate`.

----

```
extern int g(int);
//int g(int x) { return x; }
int test(int x)
{
    return (g(x) - g(x) == 0);
}
```

And:

```
v1 <- load_crucible_llvm_module "so.bc";
let v2 =
    do {
        v3 <- crucible_fresh_var "args[0]" (llvm_int 32);
        rnd <- crucible_fresh_var "ret" (llvm_int 32);
        crucible_return (crucible_term rnd);
        // crucible_execute_func [crucible_term v3];
        // XXX crucible_no_simulate ???
    };
gSpec <- crucible_llvm_verify "g" [] v2 abc;
let v5 =
    do {
        v6 <- crucible_fresh_var "args[0]" (llvm_int 32);
        crucible_execute_func [crucible_term v6];
        crucible_return (crucible_term {{ 1:[32] }});
    };
v7 <- crucible_llvm_verify "test" [gSpec] v5 abc;
```

**Comment by atomb** [comment]
The Crucible backend is structured slightly differently from the LSS, with the goal of having a `CrucibleSetup` block focus on interfaces and not execution or verification tactics. So we already have this feature, it's just in a different place. You can use `crucible_llvm_unsafe_assume_spec` to assume a spec holds without verifying it.

**Comment by TomMD** [comment]
Ah, thanks.
