### ISSUE TITLE
CI broken due to GitHub Actions moving from Docker Compose v1 to v2

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/saw-script#2086]
Due to a recent [GitHub Actions runner change](https://github.com/actions/runner-images/issues/9692), runners have now dropped Docker Compose v1 in favor of v2. One of the more notable changes in v2 is that the `docker-compose` executable is no longer available, as one is intended to use `docker compose` (without a hyphen) instead. Unfortunately, our CI currently expects `docker-compose` (with the hyphen), which causes CI to fail with the following error ([example](https://github.com/GaloisInc/saw-script/actions/runs/10213709066/job/28261254214#step:5:1)):

```
/home/runner/work/_temp/09281912-1902-40ae-8041-59f8afe8b874.sh: line 1: docker-compose: command not found
```

We should repair the CI. It might be as simple as replacing `docker-compose` with `docker compose`—worth trying.

**Comment by Yiin** [comment]
Just wanted to say thank you for creating this issue with clear description, docker-compose was failing in my builds and I was so lost why that was happening.
