### ISSUE TITLE
llvm_symexec does not typecheck its term arguments

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#21]
The `llvm_symexec` command takes as one of its arguments a value of type `[(String, Term, Int)]`, which specifies the function inputs. If the user provides terms whose types do not match the types in the llvm file, then `llvm_symexec` will result in a term that is not type correct. This can cause all sorts of weird problems later. See #19 for an example.

To ensure that only type-correct terms are created, `llvm_symexec` should compare the term types with the types of the corresponding llvm arguments, and report an error if they do not match.

**Comment by atomb** [comment]
We're going to remove the underlying code shortly, so this ticket won't be relevant.

**Comment by atomb** [comment]
We're about to merge a PR that removes `llvm_symexec`.
