### ISSUE TITLE
Update pypi to use latest cryptol python package

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#2101]
Cryptol 3.2 has been released but the `saw-client` python package depends on `cryptol==3.1.1`.

```saw-client 1.1.1 requires cryptol==3.1.1, but you have cryptol 3.2.0 which is incompatible.```

Are there plans to update `saw-client` to use `cryptol` version `3.2.0`?

**Comment by andrew-bivin** [comment]
Thanks, @weaversa . We'll address this ASAP

**Comment by andrew-bivin** [comment]
@weaversa we anticipate having a new SAW release ready by early next week, including a fix for this.

**Comment by mccleeary-galois** [comment]
@weaversa We wanted a few tickets to land for SAW which have now and we will be starting the process for release.

**Comment by mccleeary-galois** [comment]
All dependencies have been updated and released and SAW is now being prepared for release here https://github.com/GaloisInc/saw-script/pull/2113.

**Comment by mccleeary-galois** [comment]
saw-client 1.2 has been release to PyPI here https://pypi.org/project/saw-client/1.2/
