### ISSUE TITLE
Compute Coverage CI failing

### ISSUE THREAD

**Issue by mccleeary-galois** [GaloisInc/saw-script#2114]
## Summary

Compute coverage CI is failing due to some sort of version issue. 

[Here](https://github.com/GaloisInc/saw-script/actions/runs/10638908048/job/29496153758?pr=2112#step:12:30) you can see that the compute-coverage.sh is grabbing multiple versions from the dist-newstyle for this loop [here](https://github.com/GaloisInc/saw-script/blob/47a7632c973df3fdb2d32268edc92948fc150f2d/compute-coverage.sh#L23)

```
hpc markup 
--destdir=hpc-html 
--hpcdir=dist-newstyle/build/x86_64-linux/ghc-9.4.8/saw-script-1.2.0.99/hpc 
--hpcdir=dist-newstyle/build/x86_64-linux/ghc-9.4.8/saw-script-1.1.0.99/hpc/vanilla/mix/integration_tests 
--hpcdir=dist-newstyle/build/x86_64-linux/ghc-9.4.8/saw-script-1.1.0.99/hpc/vanilla/mix/saw 
--hpcdir=dist-newstyle/build/x86_64-linux/ghc-9.4.8/saw-script-1.1.0.99/hpc/vanilla/mix/saw-script-1.1.0.99 all.tix
``` 

Note the mismatch version numbers.

Cabal versions were updated in this PR from `1.1.0.99 -> 1.2.0.99`. Need to examine why `compute-coverage.sh` is grabbing both.

## Acceptance Criteria

`compute-coverage.sh` no longer fails on PRs which bump cabal version numbers

## Do
- [x] Label appropriately
- [ ] Have a working compute-coverage.sh on PRs that bump cabal version numbers
- [ ] Update Changelog and other documentation appropriately

**Comment by sauclovian-g** [comment]
compute-coverage.sh just grabs everything in dist-newstyle, so it'll never work across a version bump without cleaning the old version.

(it doesn't quite grab _everything_, which is why the list above has only the top dir shown for 1.2.0.99; but anyway it ought to do something else to find the top hpc dir.)

anyway don't spend any more time chasing after this now, we can fix it later

**Comment by kquick** [comment]
This is what the `CABAL_CACHE_VERSION` is intended to handle.  I bumped this in https://github.com/GaloisInc/saw-script/pull/2113/commits/d6b6062f3c1350b6b020f92da348320402a013a2 and the build is successful.

To be clear, the issue arises when the version number of the saw package is updated in its cabal file, not when the version of the cabal tool itself is changed.  Trying to automate this would involve detecting the current version number in the cabal file and then updating the `find` in the CI to ignore other versions; this can be done, but it may be simpler just to document that the `CABAL_CACHE_VERSION` should be updated as part of the release process (and in the same or subsequent commit that changes the saw-script version in its cabal file).

**Comment by RyanGlScott** [comment]
Bumping `CABAL_CACHE_VERSION` does suffice as a workaround. That being said, it really shouldn't be _necessary_ to do this. It should suffice to run `find -name hpc` in the specific subdirectory of `dist-newstyle` that contains the particular version of `saw-script` you care about.

Unfortunately, I'm not aware of a command that grabs this specific subdirectory. We can get pretty close, however. If we run the following command after building `saw-script`:

```
$ ghc-pkg --package-db dist-newstyle/packagedb/ghc-${GHC_VER} describe saw-script --simple-output
```

Then, among other output, we see:

```
import-dirs:
    /home/ryanscott/Documents/Hacking/Haskell/saw-script/dist-newstyle/build/x86_64-linux/ghc-9.4.8/saw-script-1.0.0.99/build
```

And that is _almost_ the directory you need to search for `.tix` files (just replace `.../build` with `.../hpc`).

**Comment by sauclovian-g** [comment]
That's straightforward to handle with shellscript; I'll go fix it tonight

**Comment by sauclovian-g** [comment]
With that technique we still have to guess $GHC_VER. I think using cabal list-bin will work better, since the suffix on that (build/saw/saw) isn't going to change.
