### ISSUE TITLE
Allow duplicate method names in Java

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/saw-script#212]
Currently, when attempting to load a method from a Java class, the name of that method must be unique. This is a frustrating limitation.

**Comment by jpziegler** [comment]
Consider using JVM type signatures, as specified here:

http://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/types.html#wp276

**Comment by atomb** [comment]
We've been considering using exactly that approach. Thanks for creating a ticket for it!
