### ISSUE TITLE
Allow printing of SetupValues

### ISSUE THREAD

**Issue by jldodds** [GaloisInc/saw-script#215]
Previous behavior printed counter examples in an "encountered, expected" format. When a proof fails it would be particularly useful to see the counterexample in the state where the assertion is checked, in particular for the LLVM, which is often harder to run outside of SAW. A straightforward way of achieving this without making default prints too verbose might be to allow the printing of SetupValues.

**Comment by siddharthist** [comment]
@jldodds We can now print `SetupValue`s, can you elaborate a bit on "see the counterexample in the state where the assertion is checked"?

**Comment by brianhuffman** [comment]
Here's my understanding of what the problem is: If you have a C program containing an assertion like `assert(x < 10)`, and that assertion fails, then just printing a list of the initial values of the function arguments is insufficient; we really would like to see the value of `x` as well.

**Comment by atomb** [comment]
This will be subsumed by other work and doesn't have much explanation included that we need to keep track of.
