### ISSUE TITLE
Error: "Verifier.SAW.Simulator.Prims.iteOp: malformed arguments: 9 10"

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#216]
This error message shows up in calls to `crucible_llvm_verify` when you have a C/LLVM function that returns a pointer whose allocation unit is not statically known. E.g., the function might conditionally return either pointer `a` or pointer `b`, where `a` and `b` point to different allocation units, and the condition is symbolic.

The problem is that the generated saw-core term contains symbolic conditional expressions of type `Nat`, and the saw-core prover backends currently do not support symbolic `Nat` values.

To fix this properly, we'll have to add support for symbolic `Nat` expressions in the proof backends. But for now, there is a workaround. Use the following saw-script command to generate a rewrite rule:
```
let equalNat_ite = core_axiom
  "\\(x y z :: Nat) (b :: Bool) -> eq Bool (equalNat x (ite Nat b y z)) (ite Bool b (equalNat x y) (equalNat x z))";
```
The effect of the rewrite rule is to pull each `Nat` conditional outward, so that it turns into an if-then-else on type `Bool`. Just apply the rewrite rule as a preprocessing step in the proof script, e.g. `do {simplify (addsimp equalNat_ite basic_ss); z3;}`.

**Comment by max-orhai** [comment]
I'm trying to apply this workaround, but it doesn't seem sufficient.

**mal.c**:
```c
#include <stdint.h>
#include <stdlib.h>

typedef struct { uint8_t* l; uint8_t* r; } Opt2;

Opt2* dec(uint32_t n) {
    Opt2* p = (Opt2*) malloc(sizeof(Opt2));
    p->l = NULL; p->r = NULL;
    if (n & 1<<24) { uint8_t l = n>>16 & 0xff; p->l = &l; }
    if (n & 1<< 8) { uint8_t r = n     & 0xff; p->r = &r; }
    return p;
}
```

**mal.saw**:
```
m <- llvm_load_module "mal.bc";

let equalNat_ite = core_axiom
    "\\(x y z : Nat) (b : Bool) -> eq Bool (equalNat x (ite Nat b y z)) (ite Bool b (equalNat x y) (equalNat x z))";

do { simplify (addsimp equalNat_ite basic_ss); abc; };

crucible_llvm_verify m "dec" [] false do {
    n <- crucible_fresh_var "n" (llvm_int 32);
    crucible_precond {{
        ltag != 1 /\ rtag != 1
        where [ltag, lval, rtag, rval] = split`{4} n }};
    crucible_execute_func [crucible_term n];
    po <- crucible_fresh_pointer (llvm_type "%struct.Opt2");
    crucible_return po;
    crucible_points_to po (crucible_struct [crucible_null, crucible_null]);
} abc;
```

If the precondition holds, both pointers within the struct should be null in this case. I need to handle the other three cases too, but this is the simplest one.

**Comment by brianhuffman** [comment]
In `mal.saw` you're not actually calling `simplify` in the proof script for `crucible_llvm_verify`, as you have still specified `abc`. Instead you should try
```
let tac = do { simplify (addsimp equalNat_ite basic_ss); abc; };

crucible_llvm_verify m "dec" [] false do {
    n <- crucible_fresh_var "n" (llvm_int 32);
    crucible_precond {{
        ltag != 1 /\ rtag != 1
        where [ltag, lval, rtag, rval] = split`{4} n }};
    crucible_execute_func [crucible_term n];
    po <- crucible_fresh_pointer (llvm_type "%struct.Opt2");
    crucible_return po;
    crucible_points_to po (crucible_struct [crucible_null, crucible_null]);
} tac;
```
or just put the `do` expression for the proof script in-line.

**Comment by brianhuffman** [comment]
When I try this example now, I get a proper proof failure with a counterexample:
```
Subgoal failed: dec safety assertion: null-equality postcondition
SolverStats {solverStatsSolvers = fromList ["ABC"], solverStatsGoalSize = 112}
----------Counterexample----------
("n",33024)
```
In hex, 33024 is 0x8100. It looks to me like this is a genuine counterexample.

**Comment by max-orhai** [comment]
Thanks! I just didn't understand how the solvers work. And you're right about the counterexample, I have a logic bug in the bit-twiddles.

**Comment by brianhuffman** [comment]
Reopening because the problem has not been fixed. We still need to implement support for symbolic expressions of type `Nat`.
