### ISSUE TITLE
SAW-Core parser parses multiple lambda arguments the wrong way around

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#227]
Basically, the SAW-Core parser interprets `\(x :: a) (y :: b) -> z` as `\(y :: b) -> (\(x :: a) -> z)`. I always wondered why I would get weird SAW-Core type errors unless I used a separate lambda for each variable, but now I know why.

Here's an example that can be reproduced in the saw-script REPL:
```
sawscript> prove_core abc "(\\(a :: Bool) (n :: Nat) -> True) False 0"

user error ("prove_core" (<stdin>:1:1):
.:1:34: Equivalence check failed during typechecking:
Prelude.Bool
and

Prelude.Nat
in context

top
)
sawscript> prove_core abc "(\\(a :: Bool) (n :: Nat) -> True) 0 False"
Theorem ((\(n::Prelude.Nat) ->
   \(a::Prelude.Bool) ->
     Prelude.True)
  0
  Prelude.False)
```

**Comment by atomb** [comment]
The refactoring by @eddywestbrook and @brianhuffman to use recursors has fixed this along the way.
