### ISSUE TITLE
LLVM intrinsic not resolved

### ISSUE THREAD

**Issue by dragostis** [GaloisInc/saw-script#229]
I'm trying to do a Rust-based `add` example translation:

```rust
#[no_mangle]
fn add(x: u32, y: u32) -> u32 {
    x + y
}
```

However, running this example yields the following error:

```
Symbolic execution failed.
Could not resolve function: llvm.uadd.with.overflow.i32
in add at internal
```

**Comment by atomb** [comment]
I think there are a handful of intrinsics we need to add support for before Rust analysis will be practical in most cases (it seems to use quite a few more than most C compilers), but we plan to get those in place soon.

**Comment by dragostis** [comment]
@atomb Anything I could help with? If the amount of effort is not extremely substantial and you think that Rust would be a viable platform for SAW, I would like to give this a try.

**Comment by atomb** [comment]
If you want to take a stab at it, a pull request would certainly be welcome! It's not likely to be a huge amount of work, though it would require some (relatively limited) understanding some of the internal data structures used by SAW for control-flow graphs and expressions.

The relevant file is here: https://github.com/GaloisInc/crucible/blob/master/crucible-llvm/src/Lang/Crucible/LLVM/Intrinsics.hs

You can see the pattern followed by the other intrinsics in that file.

We actually implemented this intrinsic in the older LLVM verification interface, but we're trying to move away from that and do most of our development on the Crucible-based system now. If you want to take a look at the other implementation, though, it's here: https://github.com/GaloisInc/llvm-verifier/blob/master/src/Verifier/LLVM/Overrides/Intrinsics.hs

**Comment by dragostis** [comment]
I'll take a look soon. In the meantime, are there any other intrinsics that I would need to add?

**Comment by atomb** [comment]
I've definitely seen the signed and unsigned versions of that intrinsic, as well as the same for subtraction and multiplication. I think `llvm.bswap` and `llvm.expect` show up sometimes. Maybe `llvm.assume`? I think that set should get you pretty far.

**Comment by siddharthist** [comment]
See also https://github.com/GaloisInc/crucible/issues/73

If anyone has a list of intrinsics that come up during Rust verification, that issue might be a good place to list them for tracking purposes.

**Comment by robdockins** [comment]
Since this bug was opened, we've added a number of intrinsics to the crucible-based verifier, in particular a collection of the `with.overflow` arithmetic functions.

It would be nice to run a couple of simple rust examples and see if we've added enough to start doing some simple verifications.

**Comment by atomb** [comment]
I've loaded a bunch of bitcode produced by recent Rust compilers at this point, and all of them have worked. So I think we can close this.
