### ISSUE TITLE
Friendly error message when classes.jar is missing

### ISSUE THREAD

**Issue by joehendrix** [GaloisInc/saw-script#23]
Currently if you omit the flag "-j classes.jar", SAWScript will complain that it can't find java.lang.Object when Java is used.  We should probably issue a specific message if Java verification is used and a classes.jar is not found.

We might trigger this is the standard classpath does not contain java.lang.Object.

**Comment by ntc2** [comment]
For example, in the case of #24 we now get
```
$ saw ffs_gen_aig.saw 
Loading module Cryptol
Loading file "ffs_gen_aig.saw"
Cannot find class java.lang.Object in codebase.

You probably forgot to specify the location of the
Java 6 standard libraries JAR using the '-j' flag. The standard
libraries JAR is called 'classes.jar' on OS X systems and 'rt.jar'
on Windows and Linux systems. Its location can be found by
running 'java -verbose 2>&1 | grep Opened', assuming you're using
a Sun Java.
```
