### ISSUE TITLE
Tutorial gives incorrect command-line arguments

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/saw-script#24]
On page 13 of sawScriptTutorial.pdf, the following assertion is made:
```
Both of these scripts can be run by saw with no arguments (though the latter must be run second, because it uses files generated by the former):
# saw ffs_gen_aig.saw
# saw ffs_compare_aig.saw
```
However, running the first of those commands results in the following error:
```
# saw ffs_gen_aig.saw 
Loading module Cryptol
Loading file "ffs_gen_aig.saw"
Cannot find class java.lang.Object in codebase.
```
This is clearly because of the first line of `ffs_gen_aig.saw`, which loads a java file:
```
cls <- java_load_class "FFS";
```

**Comment by ntc2** [comment]
The documentation needs to be fixed in any case, but fixing #23 would also give a better error message here.
