### ISSUE TITLE
Crucible LLVM support for SIMD/vector register operations

### ISSUE THREAD

**Issue by jldodds** [GaloisInc/saw-script#244]
Getting this error message when trying to store a vector. Happy to provide more details/an example if it's useful

**Comment by TomMD** [comment]
The where is straight-forward - it's in the Translation.hs of crucible-llvm:

```
    ArrayType n x -> G.arrayType (fromIntegral n) <$> toStorableType x
    VecType _ _ -> fail "Cannot directly store vector types (FIXME?)"
```

We could use the same code for `VecType` as is used for `ArrayType`.  @robdockins mentioned that we aren't actually certain of the semantics - do they differ?  Probably not, but it is worth a little thinking before we add this behavior.

**Comment by robdockins** [comment]
Indeed, my previous hesitation to simply implement vector-related operations is that I'm not sure I understand what they ought to do.  In particular, do vectors have the same memory (byte-order, etc) layout as arrays?  I don't know.

I also didn't have a clear sense of what source language constructs produce vector types.

An example would probably be useful.

**Comment by jldodds** [comment]
They are being produced by functions over the vector extension types, as in [this file](https://github.com/Shay-Gueron/AES-GCM-SIV/blob/master/AES_GCM_SIV_128/AES_GCM_SIV_128_C_Intrinsics_Code/polyval.c)

**Comment by jldodds** [comment]
I've attached a C file and the associated ll file 
[vectortest.zip](https://github.com/GaloisInc/saw-script/files/1569875/vectortest.zip)

**Comment by weaversa** [comment]
I'm running into this a well. Has there been any progress? My vectors are happening while trying to `crucible_execute_func` openssl's MD5 implementation.

**Comment by robdockins** [comment]
The proximate cause of this bug has been fixed.  Vectors can now be stored in the heap, and read back out.  We are assuming that vectors have the same memory layout as arrays.  This appears to be accurate on x86 systems, and I hope it holds in general.  I additionally fixed some related bugs with `insertelement` and `extractelement`.

However, for practical use of vector code, a few things sill need to be implemented:
* `bitcast` for vectors.  Clang will emit bitcasts to change its view on a vector, e.g. to cast between an `i128` and a `<2 x i64>` or to a `<16 x i8>`, etc.  These currently will fail.
* The `shufflevector` instruction is not currently implemented.
* There is a whole raft (hundreds) of vector-related compiler intrinsics for the various different platforms that implement them.  I don't think it's feasible to simply implement them all (at least at first), so we need some way to figure out which ones are actually necessary for examples of interest.

**Comment by robdockins** [comment]
Some additional vector support was merged in recently.  We can now handle bitcasts to/from vectors and integer values, and the `shufflevector` instruction has been implemented.

Arithmetic, bitwise, etc. operations sill need to be generalized to work over vector values, and support for intrinsics is still missing.

**Comment by robdockins** [comment]
The LLVM vector instruction support has been significantly improved since this ticket was made.  Arithmetic, bitwise instructions, GEP, etc. are now properly lifted over vector types.

For practical use of SIMD operations, additional intrinsic support will probably still be required.  However, these can be added in a pretty straightforward manner when encountered, so I'm closing this ticket for now.
