### ISSUE TITLE
coerceAny: cannot coerce from RecursiveRepr LLVM_pointer [BVRepr 64] to RecursiveRepr LLVM_pointer [BVRepr 32]

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#250]
```
coerceAny: cannot coerce from RecursiveRepr LLVM_pointer [BVRepr 64] to RecursiveRepr LLVM_pointer [BVRepr 32]
CallStack (from HasCallStack):
  error, called at src/Lang/Crucible/LLVM/MemModel.hs:358:17 in crucible-llvm-0.1-8BiYQ9z6caNIVybmYfFiSk:Lang.Crucible.LLVM.MemModel
  coerceAny, called at src/SAWScript/CrucibleBuiltins.hs:494:17 in saw-script-0.2-CBiWDUK3FYn7G4G6gi30ZF:SAWScript.CrucibleBuiltins
```

I'm not really sure what it means. I had to compile the code I have using `-m32` because 
otherwise (with a 64-bit compiled bitcode) `saw` complained in this way:

```
argument type mismatch when registering LLVM mss override Symbol "memset"
in _start at :1:0
```
where this was in the LLVM:
```
declare i8* @__memset_chk(i8*, i32, i64, i64)
```

**Comment by robdockins** [comment]
The basic problem here is that we are not being careful enough about typechecking the arguments to `crucible_exec_func`.  The result is this unilluminating error message.

**Comment by weaversa** [comment]
And memset is incorrectly specified for 64-bit builds.

**Comment by robdockins** [comment]
`memset` now has the correct type, so 64-bit builds using it should now work correctly.
