### ISSUE TITLE
Crucible and endianness

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#258]
Consider the following C code:
```c
char f(unsigned int x) {
  char *y = (char *)&x;
  return y[0];
}
```

We can compile it with `clang` for both little-endian and big-endian architectures. 

```
$ clang test.c -c -o test_LE.bc -emit-llvm
$ clang -target mips-linux-gnu test.c -c -o test_BE.bc -emit-llvm
```

And we can verify that the LLVM datalayout matches our expectations:
```
$ llvm-disasm test_LE.bc | head
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; test_LE.bc
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"
define i8 @f(i32 %0) {
; <label>: 1
  %2 = alloca i32, align 4
  %3 = alloca i8*, align 8
  store i32 %0, i32* %2, align 4
  %4 = bitcast i32* %2 to i8*
$ llvm-disasm test_BE.bc | head
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; test_BE.bc
target datalayout = "E-m:m-p:32:32-i8:8:32-i16:16:32-i64:64-n32-S64"
define i8 @f(i32 %0) {
; <label>: 1
  %2 = alloca i32, align 4
  %3 = alloca i8*, align 4
  store i32 %0, i32* %2, align 4
  %4 = bitcast i32* %2 to i8*
```

Consider the following SAW script:
```
let f_setup = do {
  x <- crucible_fresh_var "x" (llvm_int 32);

  crucible_precond {{ x == 0x01020304 }};

  crucible_execute_func [ crucible_term x ];

  crucible_return (crucible_term {{ 0x04 : [8] }});
};

test_LE_m <- llvm_load_module "test_LE.bc";
test_BE_m <- llvm_load_module "test_BE.bc";

crucible_llvm_verify test_LE_m "f" [] false f_setup z3;

crucible_llvm_verify test_BE_m "f" [] false f_setup z3;
```

Running this script shows that both bitcode files are being interpreted as little endian.
```
$ saw test.saw
Loading file "test.saw"
Proof succeeded! @f
Proof succeeded! @f
```

This issue appears to be similar #8, but for crucible rather than llvm_extract.

**Comment by brianhuffman** [comment]
Fixing this will require modifying the LLVM memory model in crucible to depend on endianness. I've done some work on that code recently, it shouldn't be too hard to implement.

**Comment by weaversa** [comment]
Thanks @brianhuffman.

**Comment by jpziegler** [comment]
This brings up some interesting questions when SAW is used to analyze *C code* (as opposed to some particular compilation into LLVM bitcode.) It can be argued that "proper" C code should be written so that it has the same functionality regardless of whether it is 32-bit, 64-bit, little-endian, or big-endian. That being the case, what can SAW do for us to help us prove that a particular piece of C code has this property? The most obvious thing would be to build a bitcode file for each of the four (or more?) cases and then run the same proof on each.

Is there anything else we can do? I see from the above thread that SAW is currently treating a big-endian bitcode as little-endian. Does that mean that a particular bitcode file has all the necessary information to do both? (My LLVM knowledge is limited.) If that's the case, then that opens up the potential for SAW to do this analysis, under-the-hood, with just a single bitcode file. My guess is that this won't work in general.

Of course, in some cases we may wish to push a proof through for some particular word size and endianness, regardless of whether the original C code was truly portable.

Thoughts?

**Comment by weaversa** [comment]
Another thought --- how does `saw` treat a (llvm_int 32)? If I compare that against a `join [4][8]` cryptol variable, will I get different answers depending on whether the LLVM was big or little endian?

**Comment by brianhuffman** [comment]
Fixed in GaloisInc/crucible@dbb61a748f7d708af1994fd25576e27a36f7cf3b and d66a84e332752a3fa66ca96e2d7a7eb9252993b2.

**Comment by brianhuffman** [comment]
Oops, it looks like I forgot to handle endianness properly when concatenating bitvectors. (The test case above only tests selection from bitvectors.) I need to create another test case for this.

**Comment by brianhuffman** [comment]
Fixed in GaloisInc/crucible@cda2b3aed366f51d9b02e2ebbf4f328d5fe7dd1e and fd149c7fc4bd78247b8c29e1847fae81706e327d.

**Comment by brianhuffman** [comment]
@jpziegler: Currently if you want to make sure your code works in either endianness you just need to verify it in both, as you suggest. I suppose we could add another "unspecified" endianness option in addition to "big" and "little", where any operation in the memory model that would require splitting or concatenating bitvectors (i.e. anything whose behavior depends on endianness) would just be undefined. If a proof succeeds in this mode, then you could be assured that it would succeed with either endianness.

**Comment by jpziegler** [comment]
@brianhuffman Thanks for the thoughts and the lightning-fast turnaround. This sounds very interesting. If I read you correctly, it seems it is indeed true that an LLVM bitcode file is largely endian-agnostic. If so, that's very interesting. I feel this could be worth exploring. I'll consider opening another ticket on the topic, given that this one is (rightly) closed.

**Comment by brianhuffman** [comment]
Well, I wouldn't say that LLVM bitcode files are endian-agnostic in general: Each one has a specific endianness encoded into its data layout string, after all. But I think it's not unusual for a particular LLVM program to be endian-agnostic, in that the program never performs any operations whose meaning is endian-dependent.

**Comment by jpziegler** [comment]
Is it possible to detect those endian-dependent operations somehow? For most of the code I look at, any such operation is likely reportable as a bug. That's really what I'm interested in with my line of questioning.

**Comment by robdockins** [comment]
Unfortunately, clang itself is very willing to make endian-aware simplifications to C code.  Constant propagation, store->load tunneling, using unions to to byte-swaping tricks, etc. will all be silently reduced by clang itself in ways that are dependent on the byte order of the system.  Even things that don't appear to depend on endian settings my *become* so when clang does an optimization.  For example, a sequence of adjacent byte stores of constant might get turned into a single i64 store by clang... and the value of the constant it chooses to store depends on the endianess.

I don't think there is any reliable way to do endianess-oblivious verification for C code using clang as a front-end.

**Comment by robdockins** [comment]
Well... let me qualify a bit.  I suppose if you compile the same C program into two different bitcode files with different endianness conventions and prove they have the same behavior, you could at least show that the program doesn't have behavior that depends on endinaness.

**Comment by robdockins** [comment]
@weaversa 
> Another thought --- how does saw treat a (llvm_int 32)? If I compare that against a join [4][8] cryptol variable, will I get different answers depending on whether the LLVM was big or little endian?

The meaning of a `llvm_int 32` is independent of the endianness assumption; it's just a 32-bit value.
Cryptol makes a particular endianness assumption, so the result of a Cryptol `join` should always be the same regardless of the endianness assumption of the LLVM code.

**Comment by robdockins** [comment]
@jpziegler, I guess it might be possible to add some sort of strict checking mode to the LLVM memory model and fail if we ever perform some operations whose result depends on endianess.  That doesn't, however, deal with the issue I mentioned above, where clang will happily do endian-dependent things for you.
