### ISSUE TITLE
OpenSSL AES Example

### ISSUE THREAD

**Issue by WeeknightMVP** [GaloisInc/saw-script#259]
Thank you for providing an [OpenSSL AES example](https://github.com/GaloisInc/saw-script/tree/master/examples/openssl_aes).  I tried running it today, but it didn't work at first.  I don't know yet how to update it to verify the current version of OpenSSL ([1.1.0g](https://www.openssl.org/source/)) because it uses a different build system, no longer providing a `Makefile` in `crypto/aes`.  However, we could update the example to enumerate and configurably invoke dependencies on [`cryptol`](https://github.com/GaloisInc/cryptol) and [`llvm-verifier`](https://github.com/GaloisInc/llvm-verifier) that are not included in [nightly builds](https://saw.galois.com/builds/nightly).  (Are these dependencies included in other builds, e.g. [Homebrew](http://brew.sh/)?)

Furthermore, in the process of updating the example, I observed that setting SAW's `--import-path` command line option apparently had no effect:

```sh
> saw -i /home/ubuntu/workspace/cryptol/share/doc/cryptol/examples aes.saw
 Loading file "/home/ubuntu/workspace/saw/examples/openssl_aes/aes.saw"
 user error (Cryptol error:
 [error] can't find file: AES.cry)
```

The following revisions would make it easier for a user to set up and try the example:
 - [README.md](https://github.com/GaloisInc/saw-script/blob/master/examples/openssl_aes/README.md)
```Markdown
The `Makefile` in this directory automatically downloads and compiles
OpenSSL, and then extracts the relevant LLVM bitcode file. However, this 
example has the following dependencies, assumed to be located in a `deps` 
folder relative to SAW's root directory:
  - [Cryptol](https://github.com/GaloisInc/cryptol) ([AES.cry](https://github.com/GaloisInc/cryptol/blob/master/examples/AES.cry))
  - [LLVM Verifier](https://github.com/GaloisInc/llvm-verifier) ([sym-api.h](https://github.com/GaloisInc/llvm-verifier/blob/master/sym-api/sym-api.h))
```
 
 - [Makefile](https://github.com/GaloisInc/saw-script/blob/master/examples/openssl_aes/Makefile)
```Makefile
# Externalize dependency references.
DEPS?=../../deps
CRYPTOL?=${DEPS}/cryptol
LLVM_VERIFIER?=${DEPS}/llvm-verifier

CRYPTOLPATH?=${CRYPTOL}/share/doc/cryptol/examples

# Set environment variable for SAW to locate AES specification.
# (Only necessary if SAW --import-path command line option does not work.)
export CRYPTOLPATH := ${CRYPTOLPATH}

# ...

# Pass `--import_path` command line option to SAW:
aes_ref.aig: aes_imp.aig aes.saw
	${SAW} --import-path=${CRYPTOLPATH} aes.saw
```
 
 - [aes.saw](https://github.com/GaloisInc/saw-script/blob/master/examples/openssl_aes/aes.saw)
```
// Use CRYPTOLPATH to locate AES specification.
import "AES.cry";
```

**Comment by WeeknightMVP** [comment]
I figured out how to run the example for [OpenSSL 1.1.0g](https://www.openssl.org/source/), the latest stable version as of Nov 2017.  To "make" it work with OpenSSL's new build system, I changed the example `Makefile` target for `aes_core.o` to:

```Makefile
${SRCDIR}/crypto/aes/aes_core.o: ${SRCDIR}/Makefile
	(cd ${SRCDIR} && make CC="${CLANG}" crypto/aes/aes_core.o)
```

However, the library layout and API have also changed slightly, requiring tweaks to `aes_wrap.c`:

```C
#include <openssl/aes.h> // aes.h is now in {source}/include/openssl/
// ...
int r = AES_set_encrypt_key(key, 128, &rkey);  // instead of private_AES_set_encrypt_key
```

The whole process took about 12 minutes on my legacy Cloud9 workspace:
```
Loading OpenSSL implementation
Time: 0.213131s

Bitblasting Cryptol implementation
Time: 1.953847s

Checking equivalence (may take about an hour)
Time: 714.400439s

Valid
Writing reference AIG
Time: 6.022388s
```

**Comment by atomb** [comment]
Thanks! I've incorporated your second set of changes, and I'll add your first set soon.
