### ISSUE TITLE
at internal: Invalid GEP

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#260]
We're seeing an error loading LLVM modules. These modules were loading just fine using the (ae39976) version of `saw`. Now loading these modules (via `llvm_load_module`) cause `saw` to say
```
at internal: Invalid GEP
getelementptr inbounds [10 x i32], [10 x i32] @F,
                                                            i32(i8*, ...)* @F
```
Any help would be greatly appreciated.

**Comment by weaversa** [comment]
I commented out all `printf` statements in the code and now things are working.

**Comment by atomb** [comment]
Try with the latest version. I believe this is fixed now.

**Comment by weaversa** [comment]
The versions I'm trying is (42c9434) and it is not working.

**Comment by weaversa** [comment]
But it was working with (ae39976) so the problem happened between these two commits.

**Comment by weaversa** [comment]
Do you think (8d91ece) fixed it? I can't check from where I am now.

**Comment by atomb** [comment]
It's commit (8d91ece) that I think fixed it. The fix is in the `llvm-pretty-bc-parser` package, and that commit just changes the version that `saw-script` depends on.
