### ISSUE TITLE
Check that assumptions are satisfiable

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#265]
It would be convenient to check that specification preconditions are satisfiable, since unsatisfiable preconditions are almost certainly a mistake (unless being used to disallow a function from being called). It may make sense to do this by checking the satisfiability of the path condition right before starting symbolic execution, to ensure that we keep track of all conditions that have accumulated, whether implicit or explicit.

**Comment by langston-barrett** [comment]
This is done for Crucible/LLVM, but not elsewhere: https://github.com/GaloisInc/saw-script/blob/90cd4da9388737ea12847ebcb7f138684d2b0411/src/SAWScript/Crucible/LLVM/Override.hs#L500-L504

**Comment by jldodds** [comment]
I'm still interested in this issue, although it could definitely introduce performance problems as well.

I'd also like a prove command that checks for trivial implication proofs. Does that belong in this issue or should it have its own?
