### ISSUE TITLE
SMT Lib

### ISSUE THREAD

**Issue by Tim-Nosco** [GaloisInc/saw-script#266]
### Setup:
```bash
clang -O3 -emit-llvm -c sha1-fast_new.c;
llvm-dis-3.8 sha1-fast_new.bc;
saw sha1.saw;
```
### Description:
The output SMT of [sha1.saw][1],  [sha1_compress.vc5.smt2][3], is very inefficient. 
The source file: [sha1-fast_new.c][2] implements `sha1_compress`.
This function does a single round of sha1 given state and block arrays.
The goal is for saw to find 4 bytes of the block variable that result in a state of all zeros.
Saw successfully finds the counterexample, but upon reviewing the SMT, it is doing a strange sequence of `ite`, `concat`, and `extract`. 
This is not obviously reflected in the `.ll` file generated in the setup step.

[1]: https://github.com/GaloisInc/saw-script/files/1724344/sha1.txt 
[2]: https://github.com/GaloisInc/saw-script/files/1724345/sha1-fast_new.txt
[3]: https://github.com/GaloisInc/saw-script/files/1724347/sha1_compress.vc5.txt

**Comment by weaversa** [comment]
This does look very strange. The `ite` statements specifically. They are effectively `ite(x, True, False)`.

Do these unnecessary statements also exist in the saw core? If so, an optimization here might help speed up symbolic execution, as well as solving.

**Comment by atomb** [comment]
Ah, interesting. Yes, there's probably just a rule that should be in the default simplification set but isn't. Or there may be several. That should be easy to fix.

**Comment by brianhuffman** [comment]
The SMTLib expression `(ite x #b1 #b0)` is a standard way to convert from type `Bool` to type `BitVec 1`, which are distinct types in SMTLib. Similarly, `(distinct #b0 x)` is a standard way to convert from `BitVec 1` to `Bool` (the other common way would be `(= #b1 x)`).

It looks like this example does some redundant conversions from `BitVec 1` to `Bool` and then back to `BitVec 1`. We could prevent redundant conversions by either making the SBV library recognize and remove them. Or we could modify saw to represent booleans as *either* a `BitVec 1` or a `Bool`, and avoid making conversions until absolutely necessary. It wouldn't be trivial to implement, but it would be straightforward.

**Comment by brianhuffman** [comment]
It looks like there are some other inefficiencies in the example SMT file, where some input bytes are being exploded out into individual bits, and then concatenated back together. I think it has to do with our implementation of the LLVM zero-extend operation. I'm looking into it.

**Comment by brianhuffman** [comment]
In GaloisInc/saw-core@447ec54d7ce733a653f6494e737c79ddd80c50df and ab94b0cd64606fd7b942f56dfeebca41d55ad3c9, I changed the implementation of the saw-core zero-extend operator `bvUExt` to avoid unpacking and repacking its bitvector argument.

sha1_compress.vc5.smt2 looks much more reasonable now:
```
; Automatically created by SBV on 2018-02-21 13:07:06.386526 PST
(set-option :smtlib2_compliant true)
(set-option :diagnostic-output-channel "stdout")
(set-option :produce-models true)
(set-logic QF_BV)
; --- uninterpreted sorts ---
; --- literal constants ---
(define-fun s_2 () Bool false)
(define-fun s_1 () Bool true)
(define-fun s4 () (_ BitVec 24) #x000000)
(define-fun s6 () (_ BitVec 32) #x00000018)
(define-fun s11 () (_ BitVec 32) #x00000010)
(define-fun s23 () (_ BitVec 32) #x00000008)
(define-fun s34 () (_ BitVec 32) #x5a827999)
(define-fun s40 () (_ BitVec 32) #x00000000)
(define-fun s14 () (_ BitVec 32) #x00000010)
(define-fun s26 () (_ BitVec 32) #x00000008)
; --- skolem constants ---
(declare-fun s0 () (_ BitVec 8)) ; tracks user variable "x0"
(declare-fun s1 () (_ BitVec 8)) ; tracks user variable "x1"
(declare-fun s2 () (_ BitVec 8)) ; tracks user variable "x2"
(declare-fun s3 () (_ BitVec 8)) ; tracks user variable "x3"
; --- constant tables ---
; --- skolemized tables ---
; --- arrays ---
; --- uninterpreted constants ---
; --- user given axioms ---
; --- formula ---
(define-fun s5 () (_ BitVec 32) (concat s4 s0))
(define-fun s7 () (_ BitVec 32) (bvshl s5 s6))
(define-fun s8 () (_ BitVec 32) (bvlshr s7 s6))
(define-fun s9 () Bool (= s5 s8))
(define-fun s10 () (_ BitVec 32) (concat s4 s1))
(define-fun s12 () (_ BitVec 32) (bvshl s10 s11))
(define-fun s13 () (_ BitVec 32) ((_ extract 31 0) s12))
(define-fun s15 () (_ BitVec 32) (bvashr s13 s14))
(define-fun s16 () (_ BitVec 32) ((_ extract 31 0) s15))
(define-fun s17 () Bool (= s10 s16))
(define-fun s18 () Bool (and s9 s17))
(define-fun s19 () (_ BitVec 32) (bvlshr s12 s11))
(define-fun s20 () Bool (= s10 s19))
(define-fun s21 () Bool (and s18 s20))
(define-fun s22 () (_ BitVec 32) (concat s4 s2))
(define-fun s24 () (_ BitVec 32) (bvshl s22 s23))
(define-fun s25 () (_ BitVec 32) ((_ extract 31 0) s24))
(define-fun s27 () (_ BitVec 32) (bvashr s25 s26))
(define-fun s28 () (_ BitVec 32) ((_ extract 31 0) s27))
(define-fun s29 () Bool (= s22 s28))
(define-fun s30 () Bool (and s21 s29))
(define-fun s31 () (_ BitVec 32) (bvlshr s24 s23))
(define-fun s32 () Bool (= s22 s31))
(define-fun s33 () Bool (and s30 s32))
(define-fun s35 () (_ BitVec 32) (bvor s7 s12))
(define-fun s36 () (_ BitVec 32) (bvor s24 s35))
(define-fun s37 () (_ BitVec 32) (concat s4 s3))
(define-fun s38 () (_ BitVec 32) (bvor s36 s37))
(define-fun s39 () (_ BitVec 32) (bvadd s34 s38))
(define-fun s41 () Bool (= s39 s40))
(define-fun s42 () Bool (and s33 s41))
(assert s42)
(check-sat)
```
I'm leaving the issue open for now because I suspect that a similar problem will arise with the signed-extension operator. I'll close when that one is fixed too.

**Comment by Tim-Nosco** [comment]
Thank you.
