### ISSUE TITLE
Accept command line input

### ISSUE THREAD

**Issue by jldodds** [GaloisInc/saw-script#267]
The ability to accept and branch on command line input to SAW would help greatly with integration, where I often need to break up proofs into hour-long chunks to fit under Travis CI limits.

**Comment by atomb** [comment]
There is the `get_opt` command, to retrieve command-line options. The ability to make decisions based on inputs is somewhat limited, though.

**Comment by jldodds** [comment]
Thanks. Closing this one and opening a new one for making decisions
