### ISSUE TITLE
Ability to branch on strings

### ISSUE THREAD

**Issue by jldodds** [GaloisInc/saw-script#268]
When using ```get_opts``` to get command line arguments, I would like to be able to compare against the string I've received.

**Comment by weaversa** [comment]
SAW does have the ability to branch on strings (though the `if` statement is not documented in the repl). I've never used `get_ops`, but coercing into a cryptol type should be possible.

Then: `sawscript> if (eval_bool {{ "cat" == "dog" }}) then print "hi" else print "bye"`

**Comment by brianhuffman** [comment]
What's missing is a way to use a saw-script `String` value within the Cryptol brackets `{{` `}}`. Currently saw-script adds `Term` variables to the cryptol context; also `Int` variables are added as cryptol numeric type variables. We could do something similar with saw-script `String` variables: they could be added to the cryptol context as values of type `[n][8]`.

**Comment by brianhuffman** [comment]
In revision e89a291, saw-script now adds `String` variables to the Cryptol context with the appropriate string type. So now you can do things like this:
```
sawscript> let str = get_opt 0
sawscript> print {{ str }}
[115, 97, 119]
sawscript> eval_bool {{ str == "saw" }}
true
```
