### ISSUE TITLE
Symbolic simulation failed along some paths! Proof succeeded!

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#270]
This combination of messages appears to be contradictory, and is really confusing for users.

I think that what it really means is that there are some failing paths, but then we have proved that those paths are unreachable. If this is actually the case (we need to make sure!) then we should change the output to something more reassuring.

**Comment by robdockins** [comment]
Agreed, information about how many/which paths failed is a low-level detail of the symbolic simulator that doesn't really need to be exposed to the user.  Indeed, if the proof succeeds, it ought to mean that any failed paths were infeasible.

**Comment by brianhuffman** [comment]
How about changing the message to, `"Symbolic simulation completed with side conditions."`? I think this is still accurate but much less alarming and less likely to be misunderstood.
