### ISSUE TITLE
Interactive mode does not load on Windows 10

### ISSUE THREAD

**Issue by WeeknightMVP** [GaloisInc/saw-script#288]
```
> saw
 saw: <stdout>: commitBuffer: invalid argument (invalid character)
> saw -I
 saw: <stdout>: commitBuffer: invalid argument (invalid character)
```

**Comment by atomb** [comment]
Do you know if this is also true for Cryptol? If not, that'll narrow down what might be going wrong.

**Comment by WeeknightMVP** [comment]
The cryptol binary included with SAW runs fine (disregarding alternative interpretation of the splash logo):

```sh
> cryptol
ΓöÅΓöüΓò╕ΓöÅΓöüΓöôΓò╗ Γò╗ΓöÅΓöüΓöôΓò║Γö│Γò╕ΓöÅΓöüΓöôΓò╗
Γöâ  ΓöúΓö│Γö¢ΓöùΓö│Γö¢ΓöúΓöüΓö¢ Γöâ Γöâ ΓöâΓöâ
ΓöùΓöüΓò╕Γò╣ΓöùΓò╕ Γò╣ Γò╣   Γò╣ ΓöùΓöüΓö¢ΓöùΓöüΓò╕
version 2.5.0 (9597082)

Loading module Cryptol
Cryptol> _
```

**Comment by atomb** [comment]
Good to know! So is the failure you're observing with standalone Cryptol using the 2.5.0 release? If so, the upcoming 2.6.0 release should fix the problem.

**Comment by WeeknightMVP** [comment]
The standalone Cryptol binary and the Cryptol binary included with SAW both run with no error.  The behavior occurs with the SAW binary, not Cryptol.

**Comment by atomb** [comment]
Ah, right! Thinko on my part.

**Comment by eddywestbrook** [comment]
The fix is to run the following command in the windows shell:

```
> chcp.com 65001
```

This sets the Windows shell to use code page 65001, i.e., to use UTF-8. It should also fix the garbled SAW splash screen as well.

The question is then: how do we incorporate this into SAW, so the user doesn't have to do this manually?

For more info, look here:

https://stackoverflow.com/questions/27616611/run-time-exception-when-attempting-to-print-a-unicode-character/27622364#27622364

https://stackoverflow.com/questions/25373116/how-can-i-set-my-ghci-prompt-to-a-lambda-character-on-windows

**Comment by WeeknightMVP** [comment]
Thanks!  Running Cryptol after this command now shows the expected pretext:

```
> chcp.com 65001
Active code page: 65001
> cryptol
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.6.1 (0d0eb2c)

Loading module Cryptol
Cryptol>
```

However, on multiple Windows 10 workspaces when trying to start recent nightlies of SAW in any mode, not just interactive, since mid-July or so, instead of a `commitBuffer` error, a system error window displays "The code execution cannot proceed because libstdc++-6.dll was not found. Reinstalling the program may fix this problem."  Looks like you're already addressing this with recent commits.

**Comment by atomb** [comment]
Oh, nice, that's a much more informative error than we were getting! On our Window machines, it was just quitting without any message, with exit code 127. It took a while to track it down to `libstdc++-6.dll`, and even so we haven't quite resolved it yet. We're working on it, though.

**Comment by weaversa** [comment]
I am having this same problem. Can't run SAW on Windows 10.
