### ISSUE TITLE
Add support for output in different bases

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/saw-script#29]
Similar to Cryptol's `:set base=<number>`, add a setting to saw-script so that words get printed in a specified base. Currently only base 10 is available.

**Comment by brianhuffman** [comment]
The main place where the choice of number base is relevant is the saw-script `print` command (and also the implicit print that is called on result values at the REPL). Right now we just pass in Cryptol's `defaultPPOpts` to the pretty-printer; we just need to add pretty-printer options to the saw-script REPL state, and pass this into the `print` command. It should be possible to implement this and #28 at the same time.

**Comment by weaversa** [comment]
It would be nice to extend this capability to other printers, such as `sat_print`, and the result values in the REPL, in general.
```
sawscript> set_base 16
sawscript> time (sat_print glucose {{ \p -> DES.encrypt `0x1234 p == 0xdd1a032cfad4f2f0 }})
"Standard error from SAT solver:\nWARNING! DIMACS header mismatch: wrong number of variables.\n\n"
Sat 22136
Time:     0.697s
sawscript> time (sat glucose {{ \p -> DES.encrypt `0x1234 p == 0xdd1a032cfad4f2f0 }})
"Standard error from SAT solver:\nWARNING! DIMACS header mismatch: wrong number of variables.\n\n"
Time:     0.673s
Sat: 22136
```
