### ISSUE TITLE
ecdsa.saw 897line error

### ISSUE THREAD

**Issue by semi-kim** [GaloisInc/saw-script#292]
ecdsa.saw 897line:  java_return {{ res.r != 0 /\ res.s != 0 }};

what is it /\ ?
/\ is error!

**Comment by atomb** [comment]
The `/\` operator is logical "and". It works similarly to `&&`, but only on `Bit` values and with slightly different precedence. It was introduced in Cryptol 2.5.0.

**Comment by semi-kim** [comment]
Thank you for your quick reply.
Do you know if there is an error after the && operator?

-----------------------------------------ecdsa.saw
verifying ec_mul
saw: user error (Prover returned error:
Failed to start the external solver: fd27: hFlush: resource vanished (Broken pipe)
Make sure you can start "/usr/bin/z3"
from the command  line without issue.)
