### ISSUE TITLE
Better error message on reaching an infeasible branch

### ISSUE THREAD

**Issue by siddharthist** [GaloisInc/saw-script#296]
Right now, if I put contradictory constraints in a Crucible+LLVM context, SAW prints
```
Infeasible branch
```
It seems like it would be helpful to provide more information: why was it judged infeasible? What constraints were in effect at the time? 

The current error message also has the downside of seeming related to branch satisfiability checking.

**Comment by robdockins** [comment]
I'm not sure how to reproduce this issue in current saw.  If, for example, we state unsatisfiable preconditions in the setup block, verification simply succeeds silently succeeds (maybe not a great outcome?).  Combinations of unsatisfiable path conditions also do not seem to produce this message.
