### ISSUE TITLE
`crucible_alloc` fails to specify memory allocated by the target function

### ISSUE THREAD

**Issue by max-orhai** [GaloisInc/saw-script#302]
I'm using a SAW nightly build (2018-8-29, e61d1b4953d9d2f193b019ca5cfe13a8f85e6b88) with clang-4.0 on Ubuntu 18.04. 

I would like to verify a function which allocates and initializes a new struct, returning a pointer to it.

**mal.c**:
```c
#include <stdlib.h>

typedef struct { char* l; char* r; } s;

s* f() {
    s* p = (s*) malloc(2);
    p->l = NULL; p->r = NULL;
    return p;
}
```

**mal.saw**:
```
m <- llvm_load_module "mal.bc";

crucible_llvm_verify m "f" [] false do {
    crucible_execute_func [];
    p <- crucible_fresh_pointer (llvm_type "%struct.s");
    crucible_return p;
    crucible_points_to p (crucible_struct [crucible_null, crucible_null]);
} abc;
```

This results in:
```
Symbolic execution failed.
Abort due to false assumption:
  Invalid memory region in memset
  in f at internal
Stack frame
  Allocations:
    HeapAlloc 4 0x2:[64] Mutable <malloc>
    StackAlloc 3 0x8:[64] Mutable "internal"
  Writes:
    
Base memory
  Allocations:
    GlobalAlloc 2 0x0:[64] Mutable malloc
    GlobalAlloc 1 0x0:[64] Mutable f
  Writes:
```

Am I doing something wrong here?

**Comment by brianhuffman** [comment]
The struct type `s` contains two pointers (total 16 bytes) but your call to `malloc` only asks for 2 bytes. Try changing `malloc(2)` to `malloc(16)` or `malloc(sizeof(s))`.

**Comment by max-orhai** [comment]
Thanks! I had forgotten that `malloc`'s argument was denominated in bytes, not words. Works fine when I use `sizeof`. I'm a little surprised that this passes all the tests I had for it.
