### ISSUE TITLE
ec_point_ops.cry

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#312]
In the ECDSA example (`ec_point_ops.cry`) we find line 122:

```
p.double(s) /* 17: r <- (0,0,0) and return */
```

Is double really what we want here? How about
```
{x=p.field.field_zero, y=p.field.field_zero, z=p.field.field_zero}
```

**Comment by atomb** [comment]
I wonder if @joehendrix knows what's going on there.

**Comment by weaversa** [comment]
`ec_add` is only called by `ec_full_add`. And, if `ec_add` returns (0,0,0), then `ec_double` is called on `s`. So, this is a deviation from the spec, but it seems to leave `ec_full_add` correct.

**Comment by joehendrix** [comment]
I added some discussion in a comment, and made a minor clarification to the case adding a point to its negation so I'm going to consider this closed.
