### ISSUE TITLE
SAWCore type checker messes with the types of top-level declarations

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#325]
Instead of preserving the types as written, the saw-core type checker reduces all types to whnf before they are registered in the `Module`. This is a major problem when you're trying to add rewrite rules or introduction rules to `Prelude.sawcore`, particularly ones involving `EqTrue`, or ones that are supposed to let you selectively unfold a particular definition.

**Comment by eddywestbrook** [comment]
Fixed with commit https://github.com/GaloisInc/saw-core/commit/c84144f218523f49b8a0ef18fb9229c9d428ee22
