### ISSUE TITLE
SAWCore type checker rejects uses of record projections on types defined as records

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#326]
In `Cryptol.sawcore`, type `PCmp a` is defined thus:
```
PCmp : sort 0 -> sort 0;
PCmp a = #{ eq  : a -> a -> Bool, cmp : a -> a -> Bool -> Bool };
```
I tried to state a rewrite rule that would allow users to control when to unfold the definition of function `ecEq`:
```
ecEq_unfold : (a : sort 0) -> (pa : PCmp a) -> Eq (a -> a -> Bool) (ecEq a pa) pa.eq;
ecEq_unfold a pa = Refl (a -> a -> Bool) (ecEq a pa);
```
However, the saw-core type checker rejected this type signature with the following error message:
```
saw: user error (saw/Cryptol.sawcore:1366:79:
Record field projection with non-record type
  Cryptol.PCmp a
In term:
  pa
)
```
The type checker apparently didn't bother trying to reduce the definition of `Cryptol.PCmp` before determining that it wasn't a record type.

(BTW, this attempt at making a useful rewrite rule for unfolding `ecEq` is also blocked by issue #325.)

**Comment by eddywestbrook** [comment]
Fixed by commit 35e71e08c470a6851ab02a60cd51a10a4861e651
