### ISSUE TITLE
Support for converting Cryptol values to other SAWScript types  

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#33]
It would be very useful to be able to convert Cryptol values of type `Bit`, `[n]`, or `[m][n]` respectively to saw-script values of type `Bool`, `Int`, or `[Int]`. This would make saw-script much more programmable without having to add too many primitive operators to the language.

**Comment by jpziegler** [comment]
I like this idea! The more SAWScript looks like Cryptol, the better, I think, for two reasons:

1. Cryptol is beautiful.
2. You need to know Cryptol to use much of SAWscript anyway.

In general, I am in favor of the "SAWScript is Cryptol with glue" model.

**Comment by brianhuffman** [comment]
In addition to `eval_int : Term -> Int`, it might be useful to have a function of type `Type -> Int` that can convert Cryptol size-type expressions like `{| n + 1 |}` to SAWScript `Int` values. If you just want to do arithmetic on unbounded integers in SAWScript, this would be a be a better fit than using a finite-width bitvector type.
