### ISSUE TITLE
iteOp: malformed arguments (extraFn)

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-script#332]
Consider this simple Cryptol file

    gen : [8] -> [inf][8]
    gen x = iterate step x where
      step y = y+1

    filter2: [inf][8] -> [inf][8]
    filter2 ([x]#xs) =
      if x == 2
      then xs
      else [x] # (filter2 xs)

    property ok x =
      x>2 ==> take`{4} (filter2 (gen x)) == take (gen x)

In cryptol, `:prove ok` works fine.  But if I import this into a recent SAW

    sawscript> import "extra.cry"
    sawscript> prove z3 {{ ok }}
    saw: iteOp: malformed arguments (extraFn)
    CallStack (from HasCallStack):
      error, called at src/Verifier/SAW/Simulator/SBV.hs:446:17 in saw-core-sbv-0.1-3eoYZO2TAPhLrtLrpdAzkV:Verifier.SAW.Simulator.SBV

followed by the traditional crash-and-burn exit from the REPL.

Any suggestions for a work-around?

**Comment by brianhuffman** [comment]
Ok, it looks like we just forgot to implement if-then-else on infinite stream values in the SBV backend. That error message is basically just a placeholder for a function that never got written. It should be easy to fix.

**Comment by brianhuffman** [comment]
GaloisInc/saw-core-sbv@485ff8f5f621f2b411ac33aa3d46edf1a7e6fbe0 fixes this problem for the SBV backend (including the `z3` proof command). However, it looks like there is a similar unimplemented operation in `abc` and maybe other backends; I'll close this ticket once they're all done.

**Comment by brianhuffman** [comment]
GaloisInc/saw-core-what4@3ec9b836 fixes this for the What4 backend, and GaloisInc/saw-core-aig@c9d222e8 fixes it for the AIG backend.
```
sawscript> prove z3 {{ \b -> (if b then repeat`{inf} True else repeat`{inf} False) @ 5 == b }}
Valid
sawscript> prove abc {{ \b -> (if b then repeat`{inf} True else repeat`{inf} False) @ 5 == b }}
Valid
sawscript> prove w4 {{ \b -> (if b then repeat`{inf} True else repeat`{inf} False) @ 5 == b }}
Valid
```
