### ISSUE TITLE
nested record woes

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-script#335]
Something is amiss with nested records, since the Dec 4 nightly build.

C file (record3.c):

    #include <stdint.h>

    typedef struct {uint64_t a; uint64_t b;} AB;
    typedef struct {AB c; uint64_t d;} CD;

    uint64_t foo(CD *x) {
      return x->c.a > 4 ? 0 : 1;
    };

SAWscript:

    m <- llvm_load_module "record3.bc";

    let {{ type CD = {c: {a: [64], b:[64]}, d: [64]}
           pre (x:CD) = x.c.a < 5
           }};

    let tm = crucible_term;

    let CD_setup = do {
      p <- crucible_alloc (llvm_struct "struct.CD");
      let pc = crucible_field p "c";
      a <- crucible_fresh_var "a" (llvm_int 64);
      b <- crucible_fresh_var "b" (llvm_int 64);
      crucible_points_to ( crucible_field pc "a" ) (tm a);
      crucible_points_to ( crucible_field pc "b" ) (tm b);
      d <- crucible_fresh_var "d" (llvm_int 64);
      crucible_points_to ( crucible_field p "d" ) (tm d);
      return (p, {{ {c={b = b, a = a}, d=d } }});
      };

    let foo_setup = do {
      (p,x) <- CD_setup;
      crucible_precond {{ pre x }};
      crucible_execute_func [p];
      crucible_return (crucible_term {{ 1:[64] }});
      };

    crucible_llvm_verify  m "foo" [] false foo_setup z3;

In nightlies up to Dec 3 this is fine; after, the proof fails. Printing the goal shows that in these later versions the precondition is somehow interpreted as applying to b not a.

If `CD_setup` is changed to read

      return (p, {{ d=d, {c={b = b, a = a} } }});

then these later SAWs fail with

    valPairLeft: Not a pair value: <<bitvector>>

**Comment by brianhuffman** [comment]
I see what's happening. I made some changes recently to how cryptol records are represented in saw-core. The cryptol->saw translation assumes that cryptol record values will have had their fields normalized in alphabetical order, but evidently that assumption is incorrect. So records are being translated incorrectly if the fields are given in non-alphabetical order.

It should be easy to fix.
