### ISSUE TITLE
`examples/llvm/dotprod_struct.saw` no longer works

### ISSUE THREAD

**Issue by WeeknightMVP** [GaloisInc/saw-script#336]
```
> saw examples/llvm/dotprod_struct.saw 
Loading file "examples/llvm/dotprod_struct.saw"
Running dotprod_struct
Finished running dotprod_struct
Valid
Starting verification of @dotprod_struct
Executing @dotprod_struct
user error ("llvm_verify" (examples/llvm/dotprod_struct.saw:53:15-53:26):
"abc" (examples/llvm/dotprod_struct.saw:29:24-29:27):
not app)
```

This example has remained unchanged for 3 years.  Perhaps this error is due to changes in the ABC backend or another dependency?

**Comment by brianhuffman** [comment]
This bug has to do with some changes that we made recently to how we represent proof goals. It looks like the old-style `llvm_verify` command still produces goals in the old format.
