### ISSUE TITLE
Using previous proof to speed up a next proof

### ISSUE THREAD

**Issue by Johanvdberg** [GaloisInc/saw-script#337]
I want to write an example that show how to use previous results to speed ups next proofs. Multiplication and exponents was selected, but just proving the exponent is slow than expected, and not sure the speed up will be visible. My questions:

1.  How can I speed up the proof of 

    exp_proof1 <- crucible_llvm_verify
        m "long_exp" [] false exp_setup abc;

2. Does multiplication and exponentiation give good examples?
3. The idea is to extend the example to use larger number, say 1028 bits.
4. How can time need for a proof be measured?

    time exp_proof1 <- crucible_llvm_verify
        m "long_exp" [] false exp_setup abc;

    give an error.

[multiply.saw.txt](https://github.com/GaloisInc/saw-script/files/2690152/multiply.saw.txt)

[code.c.txt](https://github.com/GaloisInc/saw-script/files/2690153/code.c.txt)

**Comment by siddharthist** [comment]
Naively, one could make two SAWscript files `slow.saw` and `fast.saw` and then run
```bash
[time](http://man7.org/linux/man-pages/man1/time.1.html) saw slow.saw
time saw fast.saw
```
to compare the speed of two proof scripts.
