### ISSUE TITLE
error using latest version of SAW

### ISSUE THREAD

**Issue by cchiw** [GaloisInc/saw-script#340]
```
Galoiss-MacBook-Pro:proof chiw$ saw fresh.saw 
Loading file "/Users/chiw/BIKE/proof/fresh.saw"
at :330:5: Specified alignment: 1
  insufficent for type: Alias (Ident "struct.double_seed_s"
```

The file fresh.saw just had
`m <- llvm_load_module "path/a.bc";`

**Comment by robdockins** [comment]
After discussing this with @brianhuffman, I think that the error condition being reported here isn't actually an error, and that I need to remove this check.

**Comment by robdockins** [comment]
This issue should be fixed now.
