### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by Johanvdberg** [GaloisInc/saw-script#341]
Compiling the latest version I get the error 

     Preprocessing library for what4-abc-0.1..
    Building library for what4-abc-0.1..
    [1 of 1] Compiling What4.Solver.ABC ( src/What4/Solver/ABC.hs, .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/What4/Solver/ABC.o )
    
    /Users/johan/git/saw-script/deps/crucible/what4-abc/src/What4/Solver/ABC.hs:385:14: error:
        Not in scope: ‘AIG.popCount’
        Neither ‘Data.AIG.Interface’ nor ‘Data.AIG.Operations’ exports ‘popCount’.
        |
    385 |       BV <$> AIG.popCount g x
        |              ^^^^^^^^^^^^

The git hash given by `git rev-parse HEAD` is
    

    fb6328ed48c04b43efbccc0586cf17a23b75a56f

**Comment by robdockins** [comment]
I believe this is fixed as of 7bfd4f061bd5120d72d8313161cb7a31ef97ac6e
