### ISSUE TITLE
Document how to use SAW with C++ bitcode

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/saw-script#358]
There should be a section in the manual on C++-specific verification concerns. I'll add to this list as I encounter more initially-confusing stuff:
 - Name mangling
 - Building and linking your (and your libraries'!) bitcode (I have a fancy Nix setup for this)
 - Initializing globals, generally 
 - Initializing globals with `llvm.global_ctors`

**Comment by siddharthist** [comment]
I've created [a wiki page](https://github.com/GaloisInc/saw-script/wiki/C---and-SAW) to hold some thoughts on the matter in the meantime
