### ISSUE TITLE
Support for printf_chk

### ISSUE THREAD

**Issue by cchiw** [GaloisInc/saw-script#359]
We get this issue:
"Could not resolve function: __printf_chk"

**Comment by brianhuffman** [comment]
Some time ago I had similar problems with `__memcpy_chk` and `__memset_chk`; those symbols were popping up when I compiled C programs that used `memcpy` and `memset` on OSX (which I suppose uses `FORTIFY_SOURCE` by default).

See GaloisInc/crucible@d964688fa and GaloisInc/crucible@f3f176b87 for the patches that added overrides for those functions. Implementing an override for `__printf_chk` should be similar. Note that the `_chk` functions may have one or two extra arguments that you will need to ignore; e.g. the 4th argument to `__memset_chk` is not used by the override.

**Comment by robdockins** [comment]
@cchiw, do you know how the program was compiled to get clang to emit `__printf_chk`?  I'm not sure how to make it happen.
