### ISSUE TITLE
generated bug when trying to load a struct

### ISSUE THREAD

**Issue by cchiw** [GaloisInc/saw-script#370]
%< --------------------------------------------------- 
  Revision:  46c26c46699dd7597edb429898dc95b2fb23bdc1
  Branch:    HEAD
  Location:  MemModel.unpackMemValue
  Message:   Crucible type mismatch when unpacking LLVM value
             *** Crucible type: IntrinsicRepr LLVM_pointer [BVRepr 64]
             *** LLVM value: <int32>
CallStack (from HasCallStack):
  panic, called at src/Lang/Crucible/Panic.hs:11:9 in crucible-0.4-JrxYEj1cU4t6aHzHz6F8hE:Lang.Crucible.Panic
  panic, called at src/Lang/Crucible/LLVM/MemModel.hs:1063:3 in crucible-llvm-0.2-HmUX5DKM3sSI0NFvuEV37O:Lang.Crucible.LLVM.MemModel
  unpackMemValue, called at src/SAWScript/CrucibleOverride.hs:1188:22 in saw-script-0.2-vktx2rgjcx9nO0oXj9YzT:SAWScript.CrucibleOverride
%< ---------------------------------------------------

**Comment by siddharthist** [comment]
What was the resolution here?

**Comment by atomb** [comment]
I wonder if something didn't get migrated when we merged the representations of bitvectors and pointers.

**Comment by cchiw** [comment]
No resolution yet. I just wanted to repost when I have a self-contained example.
