### ISSUE TITLE
memory rules have changed

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-script#374]
On a larger problem I found myself needing two overrides for a function, with differing assumptions about the initialization of pointed-to memory.  This works up to at least the Jan 31 nightly, but now fails.  Is the memory model now stricter in some way, and if so is there some way to have the two overrides work in newer versions of SAW?

Here's a small illustration of the difference; the proof of `g` works in older SAWs but in recent ones has an invalid memory load.  If it matters, I note that the proof of `g` works just fine with no overrides.

The C code:

    #include <stdint.h>

    uint8_t f(uint8_t *x, uint8_t y) {
      if (y > 0) return y;
      return x[0];
    };

    uint8_t g() {
      uint8_t a[1];
      f(a, 1);
      a[0] = 0;
      return f(a,0);
    };

with the SAWScript:

    m <- llvm_load_module "mem2.bc";

    let tm = crucible_term;
    let ty = llvm_array 1 (llvm_int 8);

    let f_setup0 = do {
        xp <- crucible_alloc_readonly ty;
        x<- crucible_fresh_var "x" ty;
        crucible_points_to xp (tm x);
        crucible_execute_func [xp, tm {{0:[8]}}];
        crucible_return (tm {{x@0}});
        };

    let f_setup1 = do {
        xp <- crucible_alloc_readonly ty;
        crucible_execute_func [xp, tm {{1:[8]}}];
        crucible_return (tm {{1:[8]}});
        };

    f0_ov <- crucible_llvm_verify m "f" [] false f_setup0 z3;
    f1_ov <- crucible_llvm_verify m "f" [] false f_setup1 z3;

    let g_setup = do {
        crucible_execute_func [];
        };

    crucible_llvm_verify m "g" [f0_ov, f1_ov] false g_setup z3;

**Comment by brianhuffman** [comment]
I'm bisecting this now...

**Comment by brianhuffman** [comment]
...and it looks like c39504376a854f741cd4fcc9353ad4a65c763816 is the first bad commit.
