### ISSUE TITLE
Remove `crucible_` prefix from names of saw-script operations

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#382]
The `crucible_` prefix is lengthy and uninformative, especially considering that the non-crucible verification commands have been recently deprecated. We should shorten all the names by removing the `crucible_` prefix.

**Comment by weaversa** [comment]
I 100% agree. I have a set of macros I use anyways, so I've redefined most of these commands already (as have others I've seen filing tickets).

**Comment by chameco** [comment]
This is possibly related to #253, as it might be nice to define e.g. `crucible_llvm_verify = llvm_verify` in the prelude to maintain backwards compatibility for a while.

More immediately, it might be viable to define each function under both names in `Interpreter.hs`, but mark the `crucible_` prefixed name as deprecated. This would require a better error message when attempting to use a deprecated or experimental name.

**Comment by brianhuffman** [comment]
Closed by #980. The old `crucible_`-prefixed names still exist for backward compatibility, so eventually (over a couple of release cycles) we might want to deprecate and then remove the old names, but I think that's a separate issue.
