### ISSUE TITLE
`in` is reserved?

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#385]
See, #384 

I can't create a Term called `in`:

```
sawscript> r <- llvm_load_module "test.bc"
sawscript> in <- llvm_load_module "test.bc"
Parse error at line 1, col 1
```

**Comment by brianhuffman** [comment]
`let x = y in z` is a valid expression form in saw-script. We also have an expression form `rec x = f x in z` for recursive bindings.
