### ISSUE TITLE
Problem with SBV backend translation

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-script#40]
The linked gist contains a Cryptol and saw-script demonstration of the problem.  
https://gist.github.com/robdockins/d68d8f17487db793bc1b

In short, the concrete and ABC simulators for saw-core seem to be working correctly.  However, when the given Cryptol function is passed through any saw-script command backed by the SBV simulator, I get the following error message:
```
internal: Nat subtraction result must be non-negative.
```

**Comment by robdockins** [comment]
Here is a fairly minimal example demonstrating the problem:

lfsr-min.cry
```
some_bits : {n,m} (fin n, 1 <= n, fin m)
                  => [n] -> [m]
some_bits seed = [ st!0 | st <- take states ]
  where states = [seed] # states

first_bit : [16] -> [1]
first_bit seed = some_bits seed
```
 
lfsr-min.saw
```
import "lfsr-min.cry";

print {{ first_bit 0x0001 }};

res <- prove yices {{ \x -> first_bit x == 0 }};
print res;
```

**Comment by robdockins** [comment]
@brianhuffman , any idea what it would take to close this bug?  I don't really understand what the underlying issue is...

**Comment by brianhuffman** [comment]
I can't actually reproduce this bug right now; the example above just fails to terminate.

**Comment by brianhuffman** [comment]
Both the original and minimized examples seem to be working now. Closing.
