### ISSUE TITLE
Best way to generalize this to be used with more curves?

### ISSUE THREAD

**Issue by hadasz** [GaloisInc/saw-script#406]
While using this code to implement ECDSA over secp256k1, I came across this [paper](https://eprint.iacr.org/2015/1060.pdf), which presents optimized formulas that are complete on **every** prime order short weierstrass curve over a field k (k!=2,3).

If this were designed to be a resuable ECDSA library, do you think it would make sense to use generalized formulas like the ones in the paper for point addition/doubling, so that a,b can just be passed in as arguments to ec\_double and ec\_add ? Or do you think that would be too inefficient to be worth it (over just impelementing different addition/doubling functions for each curve) ?

**Comment by atomb** [comment]
You might want to look at our [cryptol-specs](https://github.com/GaloisInc/cryptol-specs) repository. We have some more general-purpose ECC code in there, and I think that would be an appropriate place to put additional, more general code. The specs in that repository are intended to be high-level and readable (though we have varying levels of success there), so a general approach would probably be warranted. For the example in this repository, it probably makes sense to leave it in a form that more closely resembles the implementation code we're using it to verify.

**Comment by hadasz** [comment]
Thanks, that's really helpful, I wasn't aware of that repo.
