### ISSUE TITLE
typeOfLLVMVal duplicates Crucible.MemModel.Value.llvmValStorableType

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/saw-script#412]
This method:
https://github.com/GaloisInc/saw-script/blob/0f85d0b9f4067c1e194aa6a3e797daaaacdac324/src/SAWScript/CrucibleResolveSetupValue.hs#L451
Duplicates the following (unexported) one from Crucible:
https://github.com/GaloisInc/crucible/blob/a9bac7723eae011d9bbce756dce1354ff68deb35/crucible-llvm/src/Lang/Crucible/LLVM/MemModel/Value.hs#L89

**Comment by robdockins** [comment]
This was fixed via 9c6d6ab041cc4ff4bb4fbde460d455b9d438845f
