### ISSUE TITLE
SAW crashes with "evalRecursorApp: non-constructor value: <<bitvector>>)"

### ISSUE THREAD

**Issue by nano-o** [GaloisInc/saw-script#437]
[gist containing the files to reproduce the error](https://gist.github.com/nano-o/e6af8c0594050a1d274f51ca2b4f0810)

**Comment by brianhuffman** [comment]
It appears that the saw-script code there is producing an invalid rewrite rule, which is then causing the rewriter to produce a corrupted, ill-typed proof goal. If we add the command `print (addsimps' [{{\x y -> divide_java x y == x/uext(y)}}] empty_ss);` we can see what the rewrite rule looks like:
```
Rewrite Rules
=============
* divide_java !2 !1 !0
  = Cryptol.ecDiv
      (Cryptol.seq
         (Cryptol.tcMul (Cryptol.TCNum 2)
            !2)
         Prelude.Bool)
      (Cryptol.PArithSeqBool
         (Cryptol.tcMul (Cryptol.TCNum 2)
            !2))
      !1
      (Prelude.coerce
         (Cryptol.seq
            (Cryptol.tcAdd !2 !3)
            Prelude.Bool)
         (Cryptol.seq
            (Cryptol.tcMul (Cryptol.TCNum 2)
               !2)
            Prelude.Bool)
         (Cryptol.seq_cong1
            (Cryptol.tcAdd !2 !3)
            (Cryptol.tcMul (Cryptol.TCNum 2)
               !2)
            Prelude.Bool
            (Prelude.unsafeAssert
               Cryptol.Num
               (Cryptol.tcAdd !2 !3)
               (Cryptol.tcMul (Cryptol.TCNum 2)
                  !2)))
         (uext !2 !3 Prelude.Bool
            Cryptol.PZeroBit
            !0))
```
We can see that the left-hand side of the rule mentions 3 bound variables (`!0`, `!1`, and `!2`) while the right-hand side additionally mentions `!3`. This violates a documented invariant of the `RewriteRule` constructor (https://github.com/GaloisInc/saw-core/blob/master/src/Verifier/SAW/Rewriter.hs#L89) which says, "Invariant: The set of loose variables in `lhs` must be exactly `[0 .. length ctxt - 1]`. The `rhs` may contain a subset of these."

To fix the problem, we could either:
* modify the code that constructs new rewrite rules to check that the invariant holds
* not trust the invariant, and double-check each rewrite rule as we use them
