### ISSUE TITLE
Bug when overriding a function with the wrong return type

### ISSUE THREAD

**Issue by pedrotst** [GaloisInc/saw-script#438]
I made the silly mistake to `crucible_llvm_unsafe_assume_spec` on a spec with the wrong return type and I get the following error
```
You have encountered a bug in Crucible's implementation.
*** Please create an issue at https://github.com/GaloisInc/crucible/issues

%< --------------------------------------------------- 
  Revision:  9c3fd3ed36d5cc01096d8a15d8e1fa731d0507d7
  Branch:    HEAD
  Location:  MemModel.unpackMemValue
  Message:   Crucible type mismatch when unpacking LLVM value
             *** Crucible type: IntrinsicRepr LLVM_pointer [BVRepr 32]
             *** LLVM value: <int30>
CallStack (from HasCallStack):
  panic, called at src/Lang/Crucible/Panic.hs:11:9 in crucible-0.5-Jh9os3JHMZy4HzRgUlv9IF:Lang.Crucible.Panic
  panic, called at src/Lang/Crucible/LLVM/MemModel.hs:1135:3 in crucible-llvm-0.3-2U1brYMwQtBCSMRKScAq4b:Lang.Crucible.LLVM.MemModel
  unpackMemValue, called at src/SAWScript/CrucibleOverride.hs:1262:22 in saw-script-0.2-HbI7zSX9eBg8MvFthqsguS:SAWScript.CrucibleOverride
%< --------------------------------------------------- 
```

Please find a minimal saw sample attached.
[mystrcmp.tar.gz](https://github.com/GaloisInc/crucible/files/3184342/mystrcmp.tar.gz)

**Comment by siddharthist** [comment]
@pedrotst I transferred this issue to saw-script because SAW usually checks whether an override has the right type.

Could you also upload the LLVM bitcode (`.bc`) file? (Just in case there are different results with different versions of Clang, compiler flags, etc).

**Comment by pedrotst** [comment]
Of course, here you go

[mystrcmp.tar.gz](https://github.com/GaloisInc/saw-script/files/3184419/mystrcmp.tar.gz)

**Comment by siddharthist** [comment]
For `crucible_llvm_verify`, return type matching happens in [the `verifyPoststate` function](https://github.com/GaloisInc/saw-script/blob/9943846d09d4adfa3766922235405d7e8616eb14/src/SAWScript/CrucibleBuiltins.hs#L807), specifically in the local function [`matchResult`](https://github.com/GaloisInc/saw-script/blob/9943846d09d4adfa3766922235405d7e8616eb14/src/SAWScript/CrucibleBuiltins.hs#L852), which calls [`matchArg`](https://github.com/GaloisInc/saw-script/blob/9943846d09d4adfa3766922235405d7e8616eb14/src/SAWScript/CrucibleOverride.hs#L927).  This is function that does the brunt of the work in matching values that come out of the simulator (Crucible) with those in the SAWscript, which are written in Cryptol. `matchArg` requires both kinds (Crucible and SAW/Cryptol) of values, and it both (1) compares them for structural compatibility and (2) asserts that they are equal. 

We need to write a function that just does the simpler check that the Cryptol value that appears in the spec is structurally compatible with the function you're overriding's declaration/defintion, and then use it in `crucible_unsafe_assume_spec`.

**Comment by siddharthist** [comment]
Probably the way this should work is that we should have a functions
```haskell
checkMethodSpecDeclare :: CrucibleMethodSpecIR -> L.Declare -> Maybe Err
checkMethodSpecDefine :: CrucibleMethodSpecIR -> L.Define -> Maybe Err
```
that check a given override against the declaration or definition in the LLVM module. These can then be shared by `crucible_llvm_verify` and `crucible_unsafe_assume_spec`.

**Comment by siddharthist** [comment]
Okay, after doing a little digging, it looks like overrides actually infer their argument/return types from the declaration/defintion in the LLVM module, so the fix should actually be to check the return type whenever we encounter a `crucible_return` statement inside a `CrucibleSetupM` block.

**Comment by siddharthist** [comment]
From a conversation with @brianhuffman and @robdockins: This kind of checking can't be done inside `CrucibleSetup` blocks, because we don't yet know which function this will be an override for (that's specified as an argument `crucible_llvm_verify` or `crucible_unsafe_assume_spec`). In particular, we don't even know what the function's signature is supposed to be. So it looks like this will have to be done in `crucible_llvm_verify` and `*_unsafe_assume_spec`.
