### ISSUE TITLE
Duplication: equalValsPred and Crucible's Value.testEqual

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/saw-script#439]
This one is my fault :) These two functions are notably similar:
[Crucible.LLVM.MemModel.Value.testEqual](https://github.com/galoisinc/crucible/blob/master/crucible-llvm/src/Lang/Crucible/LLVM/MemModel/Value.hs#L274)
```haskell
testEqual :: forall sym. (IsExprBuilder sym, IsInterpretedFloatExprBuilder sym)
          => sym -> LLVMVal sym -> LLVMVal sym -> IO (Maybe (Pred sym))
```
[SAWScript.CrucibleResolveSetupValue.equalValsPred](https://github.com/GaloisInc/saw-script/blob/typecheck-overrides/src/SAWScript/CrucibleResolveSetupValue.hs#L463)
```haskell
equalValsPred ::
  CrucibleContext wptr ->
  LLVMVal ->
  LLVMVal ->
  IO (W4.Pred Sym)
```
We should probably rephrase the latter so that it uses the former, which is more complete.

**Comment by robdockins** [comment]
This was fixed via 9c6d6ab041cc4ff4bb4fbde460d455b9d438845f
