### ISSUE TITLE
Support multi-dimensional Java arrays

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#44]
The current set of commands in the `JavaSetup` context does not support declaring or stating properties about multi-dimensional arrays.

**Comment by atomb** [comment]
We should ensure that we can do this with the Crucible-based interface to Java verification.

**Comment by brianhuffman** [comment]
The new Crucible-JVM interface *can* describe multi-dimensional arrays, but not concisely. Basically, you have to describe things as explicit arrays of arrays, with a `points_to` constraint for each element at every level.

We need to design some higher-level commands for declaring multi-dimensional arrays without all the repetition. It also might help to extend the Crucible-JVM memory model/object representation to support multi-dimensional arrays directly (so we can avoid the overhead of all the object references at intermediate levels).

**Comment by atomb** [comment]
I think the remaining work on this is encompassed in #422, so this issue can be closed.
