### ISSUE TITLE
SAW crashes with "expected Nat: subNat2"

### ISSUE THREAD

**Issue by nano-o** [GaloisInc/saw-script#445]
[https://gist.github.com/nano-o/ae32a8ae07a2b5bc0933b10899fc52f8](https://gist.github.com/nano-o/ae32a8ae07a2b5bc0933b10899fc52f8)

**Comment by siddharthist** [comment]
@nano-o I think your gist is missing the saw-script file

**Comment by nano-o** [comment]
Added the file, thanks!

**Comment by brianhuffman** [comment]
It looks like the way we translate Cryptol's `updateEnd` primitive to saw-core is problematic:
```
sawscript> prove abc {{ \(i:[4]) (j:[4]) -> updateEnd 0x0000 i True @ j }}

user error ("prove" (<stdin>:1:1-1:6):
"abc" (<stdin>:1:7-1:10):
expected Nat: subNat2)
```

**Comment by brianhuffman** [comment]
This seems very similar to issue #363, and it can probably be fixed in basically the same way (see GaloisInc/saw-core@edffc76).
