### ISSUE TITLE
Make `print` and `show` display Cryptol, Java, and LLVM module contents

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#45]
The built-in functions `llvm_browse_module` and `java_browse_class` could be made obsolete by having `print` and `show` do the same thing (instead of their current behavior of printing almost nothing). The same could work for Cryptol modules.

**Comment by brianhuffman** [comment]
Changeset 6e33bd8b5e4beb45d84b148741409f501beb554d implements this for Cryptol modules.

**Comment by brianhuffman** [comment]
Changeset 9c5c20d00f3540c44e655b2068811db07a3b1077 implements this for LLVM modules.
