### ISSUE TITLE
Organization of Crucible/LLVM related modules

### ISSUE THREAD

**Issue by siddharthist** [GaloisInc/saw-script#455]
Right now, we have a few Crucible/LLVM modules in the top level under `SAWScript` that should probably have their own submodule/path structure. This would both suggest that they are related (they are) and differentiate them from Crucible/JVM material. I'd suggest the following:
 - `CrucibleOverride` -> `LLVM.Overrides`
 - `CrucibleLLVM` -> `LLVM.Crucible`
 - `CrucibleBuiltins` -> `LLVM.Builtins`
 - `CrucibleMethodSpecIR` -> `LLVM.MethodSpec`
 - `CrucibleResolveSetupValue` -> `LLVM.SetupValue`

**Comment by atomb** [comment]
👍

**Comment by brianhuffman** [comment]
See also #379. At some point we'll want to factor out the common functionality in the crucible-llvm and crucible-jvm parts of saw-script. So we should also think about how the modules ought to be organized once that's done.

**Comment by siddharthist** [comment]
@brianhuffman I've started considering that question on a branch: https://github.com/siddharthist/saw-script/tree/crucible-llvm-jvm.

I made the module hierarchy with the following idea in mind:
 - `SAWScript.Crucible` has all Crucible-specific code
- `SAWScript.Crucible.<lang>` has crucible-<lang> specific code
 - `SAWScript.Crucible.Common` has non-language specific code

Let me know what you think!
