### ISSUE TITLE
Feature Request: Better Line Number Feedback

### ISSUE THREAD

**Issue by pedrotst** [GaloisInc/saw-script#456]
Consider this minor modification to `examples/llvm/dotprod_struct-crucible.saw`

```
...
let dotprod_spec n = do {
...
    let yval = crucible_struct [ ysp, nt ]; // line 20
    xp <- alloc_init (llvm_struct "struct.vec_t") xval;
    (yyp, yp) <- alloc_init (llvm_struct "struct.vec_t") yval; // <--- Bug introduced
...
};
...
```
Instead of reporting the bug on line 22, it reports the type mismatch on line 20, which makes it a lot harder to find the issue.

```
Loading file ".../examples/llvm/dotprod_struct-crucible.saw"
.../saw-script/examples/llvm/dotprod_struct-crucible.saw:20:9-20:13: 
type mismatch: CrucibleSetup (t.26, t.27) and CrucibleSetup SetupValue

 at "dotprod_spec" (.../saw-script/examples/llvm/dotprod_struct-crucible.saw:15:5-15:17)
type mismatch: (t.26, t.27) and SetupValue at "dotprod_spec" 
(.../saw-script/examples/llvm/dotprod_struct-crucible.saw:15:5-15:17)
```

Please find attached all the files
[dotprod_bug.tar.gz](https://github.com/GaloisInc/saw-script/files/3204861/dotprod_bug.tar.gz)

**Comment by brianhuffman** [comment]
It might not be worth putting much effort into this, as we are thinking about transitioning to the new python-based language frontend.
