### ISSUE TITLE
Module SAWScript/LLVMBuiltins has lots of compile warnings

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#461]
There are many warnings about redundant imports since revision 2d21dc2946d7e22204226a3a2430f2a14f3b4881, when a bunch of LSS code was removed.

**Comment by atomb** [comment]
Ah, good point. One thing I don't like about Stack is its tendency to hide those. I'll make a pass over the code to clean those up, since I made that commit.
