### ISSUE TITLE
Tutorial example `dotprod` fails due to unimplemented primitives

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#48]
The tutorial includes an example, `dotprod`, in the following files:

* [Cryptol](../blob/master/doc/tutorial/code/dotprod.cry)
* [C](../blob/master/doc/tutorial/code/dotprod.c)
* [SAWScript](../blob/master/doc/tutorial/code/dotprod.saw)

When running through SAW, we currently get the following output:

```
Loading module Cryptol
Loading file "dotprod.saw"
Loading module Main
saw: user error (ERROR unimplemented primitives: Cryptol.arithBinaryBool Cryptol.arithUnaryBool Cryptol.bvLg2 Cryptol.ecError Cryptol.ecRandom Cryptol.lg2Nat Cryptol.tcLenFromThenTo_Nat Cryptol.tcLenFromThen_Nat)
```

Not long ago (early July) this worked correctly.

**Comment by brianhuffman** [comment]
This error message was introduced in changeset 4880ca5f, added by @robdockins on July 21. I can go ahead and add the listed primitives to the simulator backends; as a start I'll probably have them raise run-time errors.

**Comment by robdockins** [comment]
These primitives are already implemented: see Verifier.SAW.Cryptol.Prims.

However, you need to make sure that the Cryptol primitives are installed into the various saw-core simulators.  E.g., when calling 'Verifier.SAW.Simulator.evalSharedTerm', you need to pass in 'Verifier.SAW.Cryptol.Prims.concretePrims' as the additional primitives.

**Comment by brianhuffman** [comment]
The error in `dotprod.saw` is raised by the `llvm_symexec` command. I tracked down the source of the error to the `scTermSAT` function in module `Verifier.LLVM.Backend.SAW`.

In changeset GaloisInc/llvm-verifier@e2cd40ab, `scTermSAT` (and a couple of related functions) were made to pass `Map.empty` as the set of extra primitives to `withBitBlastedPred`. This seems to be the one place to that @robdockins missed.

**Comment by robdockins** [comment]
Ah, I see.  That's a fairly annoying inversion of control problem.  The primitives that need to be passed in are defined in another package, and I don't think we want to make a dependency between those packages.  That means they have to be passed in dynamically from the calling context somehow.

Perhaps primitive definitions should be bundled together with the modules that reference them inside the SharedContext.  Then you wouldn't end up in this situation where you've loaded a sawcore module that references primitives, but not have the corresponding primitive implementations anywhere.

**Comment by robdockins** [comment]
I've temporarily changed this check to produce a warning instead of an error, until we fix the root problem.

**Comment by atomb** [comment]
In case it wasn't clear from the above, the `dotprod.saw` example does work now, but produces many warnings about unimplemented primitives.

**Comment by dylanmc** [comment]
Even though these errors are extraneous now, for really long proofs, they're a pleasant reminder that SAW is still working. I'm getting a lot of them with some LLVM experiments I'm doing, so it would be nice to get rid of them at some point. They hide the intended output.

**Comment by ntc2** [comment]
Is there any plan to eliminate these messages?

I'm seeing these "errors" now and they're confusing, since they don't appear to actually be errors. Like Dylan said, the obscure the relevant output.
