### ISSUE TITLE
Crucible/LLVM: Need to specify an allocation with mismatched size and type

### ISSUE THREAD

**Issue by siddharthist** [GaloisInc/saw-script#481]
Consider the following C code:
```c
/*
  nix-shell --pure -p "with import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-19.03.tar.gz) {}; clang_7" --run "clang -g -O0 -emit-llvm -c *.c"
  nix-shell --pure -p "with import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-19.03.tar.gz) {}; llvm_7" --run "llvm-dis *.bc"
*/

#include <stdlib.h>
#include <string.h>

struct my_struct {
  int foo;
  char bar[18];
};

// INVARIANT: *src must have four additional allocated bytes beyond
// sizeof(my_struct)!
struct my_struct *copy_my_struct(struct my_struct *src) {
  size_t sz = sizeof(struct my_struct)+4;
  struct my_struct *dest = malloc(sz);
  memcpy(dest, src, sz);
  return dest;
}
```
And the following SAW spec:
```javascript
// nix-shell --pure -p "with import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz) {}; yices" -p z3 --run "saw *.saw"
m <- llvm_load_module "test.bc";
let copy_my_struct_spec = do {
  src_struct_ptr <- crucible_alloc (llvm_type "%struct.my_struct");
  crucible_points_to (crucible_field src_struct_ptr "foo") (crucible_term {{ 0 : [32] }});
  crucible_points_to (crucible_field src_struct_ptr "bar") (crucible_term {{ zero : [18][8] }});
  crucible_execute_func [src_struct_ptr];

  dest_struct_ptr <- crucible_alloc (llvm_type "%struct.my_struct");
  crucible_points_to (crucible_field dest_struct_ptr "foo") (crucible_term {{ 0 : [32] }});
  crucible_points_to (crucible_field dest_struct_ptr "bar") (crucible_term {{ zero : [18][8] }});

  crucible_return dest_struct_ptr;
};
crucible_llvm_verify m "copy_my_struct" [] false copy_my_struct_spec z3;
```
If I run this script, Crucible will correctly tell me that the allocation I wrote in my SAWscript spec isn't large enough for this `memcpy`. However, if I were to allocate an array of chars, I would no longer be able to specify the values of my struct fields using `crucible_points_to` and `crucible_field`, making my specification unreadable. 

We should probably fix this by adding an ability to manually specify the size of an allocation while also specifying the type that SAW should treat it as having. 

Unfortunately, this scenario is based on real C code I'm trying to write overrides for (in OpenSSL), so it seems like it's a pattern that comes up in practice.

**Comment by brianhuffman** [comment]
As a workaround, maybe you could call `crucible_alloc` with a type that is just an array of bytes of the length you want, and then use `crucible_points_to_untyped` to put a (smaller) struct into it?

I guess one limitation would be that `crucible_field` wouldn't work on a pointer to an array of bytes.
