### ISSUE TITLE
CI test suite does not run saw examples in `doc/tutorial/code`

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#486]
Issue #484 was a bug that caused one of the `.saw` files in the `doc/tutorial/code` directory to fail with an error message. We should have noticed this earlier. Why are these `.saw` files not run as part of our continuous integration tests?

**Comment by atomb** [comment]
There's a set of test scripts to run most of them, but not all of them, it seems. See `intTests/test_tutorial{1,2,3,4}`. We should add the rest.

While we're at it, we should add tests for the scripts in the `examples` directory, too.

**Comment by atomb** [comment]
The new branch `at-486-tests` adds tests for the rest of the tutorial code, which demonstrates another bug. Now `des3.saw` yields `ruleOfProp: Predicate not an equation: prop1 !1 !0`.

**Comment by brianhuffman** [comment]
We should create a separate ticket for the `des3.saw` failure.
