### ISSUE TITLE
Can't parse "::" in LLVM types

### ISSUE THREAD

**Issue by siddharthist** [GaloisInc/saw-script#516]
`::` gets emitted by Clang when dealing with C++ namespaces. SAW doesn't recognize this as a valid part of an LLVM type name. 
```c++
/*
  nix-shell --pure -p "with import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-19.03.tar.gz) {}; clang_7" --run "clang++ -O0 -g -emit-llvm -c *.cpp"
  nix-shell --pure -p "with import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-19.03.tar.gz) {}; llvm_7" --run "llvm-dis *.bc"
*/

namespace quux {
class Foo {
public:
  int bar;
  int get_baz() {
    return baz;
  }
  Foo(int bar)
    : bar(bar),
      baz(bar - 2) {}
private:
  int baz;
};

}

int main() {
  quux::Foo f = quux::Foo(2);
  return f.get_baz();
}
```
```
m <- llvm_load_module "./test.bc";
let foo_type = llvm_type "%class.quux::Foo";
// also fails: llvm_type "class.quux::Foo";
```
```
[18:28:40.654] Loading file "/home/siddharthist/code/tmp/class-parse/test.saw"
[18:28:40.672] "llvm_type" (/home/siddharthist/code/tmp/class-parse/test.saw:2:16-2:25):
"<internal>" (line 1, column 12):
unexpected ':'
expecting letter, digit, "(", "*" or end of input
```
[class-parse.tar.gz](https://github.com/GaloisInc/saw-script/files/3436982/class-parse.tar.gz)

**Comment by brianhuffman** [comment]
The parser for llvm types, which is implemented in Parsec, lives in the `llvm-pretty` package: https://github.com/elliottt/llvm-pretty/blob/master/src/Text/LLVM/Parser.hs

**Comment by siddharthist** [comment]
@brianhuffman Thanks for the pointer! No wonder I was having trouble finding this in the SAW source code...

**Comment by brianhuffman** [comment]
The LLVM Language Reference section on identifiers (https://llvm.org/docs/LangRef.html#identifiers) says,

> Named values are represented as a string of characters with their prefix. For example, `%foo`, `@DivisionByZero`, `%a.really.long.identifier`. The actual regular expression used is `[%@][-a-zA-Z$._][-a-zA-Z$._0-9]*`. Identifiers that require other characters in their names can be surrounded with quotes. Special characters may be escaped using "`\xx`" where `xx` is the ASCII code for the character in hexadecimal. In this way, any character can be used in a name value, even quotes themselves. The "`\01`" prefix can be used on global values to suppress mangling.

So according to the LLVM reference, having colons in the identifier names shouldn't be allowed unless they are escaped.

Does clang actually generate human-readable `.ll` files with names like that, or do those identifier names only appear in `.bc` files?

**Comment by siddharthist** [comment]
@brianhuffman This is the output of `llvm-dis` on bitcode produced by `clang++ -emit-llvm`:
```llvm
%"class.quux::Foo" = type { i32, i32 }
```
So I guess clang is following the recommendation
> Identifiers that require other characters in their names can be surrounded with quotes.

though I would expect that to be `"%class.quux::Foo"`, rather than `%"class.quux::Foo"`. 

When I try surrounding the name with quotes in those same spots:
```
m <- llvm_load_module "./test.bc";
let foo_type = llvm_type "%\"class.quux::Foo\"";
```
I get:
```
[19:46:09.973] "llvm_type" (/home/siddharthist/code/tmp/class-parse/test.saw:2:16-2:25):
"<internal>" (line 1, column 2):
unexpected "\""
expecting letter or digit
```

**Comment by brianhuffman** [comment]
We should probably update the llvm-pretty type parser to support quoted strings and also hexadecimal escapes. I'll create a ticket on the llvm-pretty repo to that effect.

**Comment by siddharthist** [comment]
This is fixed upstream, let's leave this open until we update the `llvm-pretty` submodule.

By the way, referencing these types in SAW is now covered on the [C++ and SAW](https://github.com/GaloisInc/saw-script/wiki/CXX-and-SAW) wiki page.
