### ISSUE TITLE
Non-scalar arguments accepted by crucible_llvm_extract

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#521]
Now that pointers and integers are unified in `crucible-llvm`, running `crucible_llvm_extract` on functions taking pointer parameters results in obscure memory load failures rather than a simple message that such functions aren't supported. We should make it check more carefully.

**Comment by kryptolka** [comment]
But what can I use instead of "crucible_llvm_extract" to get the same result for function taking pointer parameters? I' struggling to generate AIG file from C void function.
