### ISSUE TITLE
Rename remaining `saw-script--` variables in `flycheck-saw-script.el`

### ISSUE THREAD

**Issue by WeeknightMVP** [GaloisInc/saw-script#538]
After installing `flycheck` via MELPA and manually installing `flycheck-saw-script.el`, Emacs 26.2 reports an error during initialization:

`Symbol's value as variable is void: saw-script--output-regexp`

Prefixing this variable name with `flycheck-` yields an error when opening a `.saw` file:

`Error from syntax checker saw-script: Symbol’s value as variable is void: saw-script--info-start-regexp`

Prefixing this with `flycheck-` evidently makes `flycheck` work with `saw-script` major mode.

**Comment by weaversa** [comment]
I tried installing this as well today and had issues. It would be nice if this worked.

**Comment by weaversa** [comment]
@chameco Thank you so much! This is great to have! Been using it all day today and it's made programming in saw-script soooooo much easier.
