### ISSUE TITLE
Add compositional verification for x86

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#554]
At the moment, x86 verification is possible but requires writing proof scripts in Haskell code. Exposing that infrastructure in a way similar to `crucible_llvm_verify` would significantly reduce the effort of doing x86 verification. Having #553 done first would be very valuable.

**Comment by brianhuffman** [comment]
Verification for x86 has been implemented by a series of PRs (#630, #651, #710, #712, #725, #753, #802, #847, #859). Are those sufficient to close this ticket?

**Comment by RyanGlScott** [comment]
> Are those sufficient to close this ticket?

Yes.
