### ISSUE TITLE
Add compositional verification for Rust

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#555]
A translator from Rust MIR to Crucible exists (https://github.com/galoisinc/mir-verifier) and a somewhat stale branch (`mir-frontend`) exposes a `mir_extract` command in SAWScript. However, exposing that infrastructure in a way similar to `crucible_llvm_verify` would make a much wider variety of verification possible. Having #553 done first would be very valuable.

**Comment by sauclovian-g** [comment]
We have ```mir_verify``` these days.
