### ISSUE TITLE
SBV->C: Unexpected: mkConst: False

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-script#6]
I've been experimenting with the C code generator.  Here's a simple test that crashes the interpreter:

  codegen "" "f" {{\ (x,y)-> (x:[2][8])@[y] }}

This prints out the makefile and f.h, then while printing f_driver.c, just after emitting the line "int main(void)" says "saw: SBV->C: Unexpected: mkConst: False" and exits.

**Comment by robdockins** [comment]
I suspect the original underlying bug here is fixed, but running this example now generates:
```
asFiniteType: unsupported argument type: #(Cryptol.ty
    (Cryptol.TCSeq (Cryptol.TCNum 2) (Cryptol.TCSeq (Cryptol.TCNum 8) Cryptol.TCBit)) | Cryptol.ty
                                                                                          (Cryptol.TCPair Cryptol.TCBit Cryptol.TCUnit))
```
I'm pretty confident this is the same problem as issue #66 .

Further, if I simplify the problem to
```
codegen "" "f" {{ \x -> (x:[2][8]) }}
```
then i instead get
```
sbvCodeGen: operations not yet supported
```

**Comment by robdockins** [comment]
Fixed by recent changes to sawcore normalization.
