### ISSUE TITLE
Yices invocation almost always fails

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#602]
A recent change in What4 led to the Yices backend erroneously thinking that Yices didn't support bit vectors. This causes some of the `saw-script` tests to fail. It looks as though @robdockins has fixed the issue, though, so we just need to update the `crucible` submodule.

**Comment by brianhuffman** [comment]
Do any of the integration tests in `intTests` use `w4_unint_yices`? If not, we should add one. I did run all the integration tests before I merged the last update-submodule-dependencies pull request.

**Comment by atomb** [comment]
Huh. Strange. Several of the `intTests` tests were failing on Jenkins overnight. I'll check locally.

**Comment by brianhuffman** [comment]
I'll try it again too. It's possible that I accidentally had the wrong submodule version checked out when I ran the tests.

**Comment by brianhuffman** [comment]
Yes, I'm seeing the failures now. I must have made some mistake yesterday when running the tests.

**Comment by brianhuffman** [comment]
I think what happened is that I actually ran the right tests, looked at the end of the output, and didn't realize that there were any failures. I opened #603 in the hope that this won't be such an easy mistake to make in the future.

**Comment by brianhuffman** [comment]
Fixed as of 4b0019bff748f56877293f6c4f9dccea501be901.
