### ISSUE TITLE
Mention `-fsanitize` options in SAW manual

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-script#611]
CF GaloisInc/crucible#368

Clang has the ability to insert additional explicit checks for C undefined behavior when compiling.  We should mention these options and suggest that users may want to enable these options if they are concerned about the portability of their code across different C compilers.

**Comment by evelynmitchell** [comment]
Would a reference to 
https://clang.llvm.org/docs/UsersManual.html#controlling-code-generation
be a suitable level of description for -fsanitize?

**Comment by atomb** [comment]
To properly support this, we'll need to add overrides for the various functions that Clang inserts calls to when its checks fail. These include, for example, `__ubsan_handle_shift_out_of_bounds`.

**Comment by robdockins** [comment]
It would be nice to have support for all those `__ubsan` handlers, but you can also use the `-fsanitize-trap` option which instead emits a `trap` intrinsic, which we already have support for.

**Comment by langston-barrett** [comment]
From a discussion on #680, where @robdockins shared an example of where this is helpful:

> One specific case I can recall: clang is happy to compile a signed right shift to a shift that doesn't have the nsw flag. Turning on the -fsantitize=shift option correctly found that overflow condition.

**Comment by atomb** [comment]
I added back the reference to `-fsanitize`, also recommended `-fsanitize-trap`, and added a test case verifying that it works as expected. Given that, I think this is ready to merge.

**Comment by atomb** [comment]
Apparently saying that a commit closes two issues separated by a comma doesn't work!
