### ISSUE TITLE
Function checkModuleCompatibility is a performance bottleneck

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#622]
Function `checkModuleCompatibility` is called by `crucible_llvm_verify` to check that each supplied override was proved using the same LLVM module.

https://github.com/GaloisInc/saw-script/blob/74ddfaf7b947bb184a0a818d540b82a36243027e/src/SAWScript/Crucible/LLVM/Builtins.hs#L270-L283

The problem is that it does a full structural comparison of the entire LLVM AST for every override, which can be expensive. Profiling shows that on some proof scripts, this can account for up to half of the total runtime of `crucible_llvm_verify`.

Instead of a full structural comparison, we should perhaps generate a unique ID for each `LLVMModule` value when the module is loaded, which we can then use for fast comparisons.

**Comment by robdockins** [comment]
Yikes! Yeah, a unique ID will catch the very common case of reusing the same module.  If we hash the module, that would also provide an additional common case for distinct modules.

**Comment by robdockins** [comment]
The relevant code is below.  Note that the `ModuleTranslation` test is already a fast `Nonce` comparison.  That test is probably sufficient, actually.

```
data LLVMModule arch =
  LLVMModule
  { _modName :: String
  , _modAST :: L.Module
  , _modTrans :: CL.ModuleTranslation arch
  }

makeLenses ''LLVMModule

instance TestEquality LLVMModule where
  testEquality (LLVMModule nm1 lm1 mt1) (LLVMModule nm2 lm2 mt2) =
    case testEquality mt1 mt2 of
      Nothing -> Nothing
      r@(Just Refl) ->
        if nm1 == nm2 && lm1 == lm2
        then r
        else Nothing
```

**Comment by brianhuffman** [comment]
Yeah, I had noticed that the `ModuleTranslation` comparison was really fast. I was thinking that I should move a bit of code around so that we can make `LLVMModule` into an abstract datatype; we can provide functions to project the components, but there's really no reason to ever *update* any of the components of an `LLVMModule` value after it's created.
