### ISSUE TITLE
Reporting LLVM function coverage

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#643]
It would be useful to be able to have saw generate a summary of which C/LLVM functions have been verified by a `crucible_llvm_verify` command, or an entire proof script. We should ask crucible to keep track of which C/LLVM function definitions are traversed during symbolic simulation, and store a summary somewhere. Then maybe we could have another saw command to print out the summary or write it to a file.

**Comment by brianhuffman** [comment]
@atomb, does #767 take care of this issue, or is there something else left to do?

**Comment by RyanGlScott** [comment]
#767 addresses the spirit of this feature request through the `summarize_verification` command, so let's close this. If there are additional enhancements that we want to make to `summarize_verification`, then we can open specific issues for those.
