### ISSUE TITLE
Sample CI script

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#681]
It would be nice to provide a "Hello World" level `.travis.yml` for projects who want to do CI using SAW. It would be nice to provide a skeleton `.yml` that, at the very least, sets up a recent or nightly `saw` build and all supported smt solvers. Is there such a thing?

**Comment by atomb** [comment]
This is one of the goals of the [saw-demos](https://github.com/galoisinc/saw-demos) repository, but that part isn't done yet. In the meantime, the [s2n](https://github.com/awslabs/s2n) setup is a reasonable reference. It does a lot more than just run SAW, though, so it's unfortunately a bit complex.
