### ISSUE TITLE
Initialize all Java fields to fresh values unless otherwise specified in `java_verify`

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#69]
When using `java_verify`, ensure that each field of a newly created object has a fresh value, rather than the default zero value. Using the proposed `java_assert_eq`, (#68) the user could overwrite this fresh value with a different value if desired, or constrain its value with the current `java_assert` command.

**Comment by brianhuffman** [comment]
The `java_verify` command is set to be removed as part of #1005, so I'm closing.
