### ISSUE TITLE
"ambiguous collection of variables"

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#691]
What does the error message mean?

**Comment by weaversa** [comment]
I think it means that crucible_fresh_var was called, but the fresh variables that were created were not tied to any input or output of the function being verified.

**Comment by atomb** [comment]
Yeah, that's basically right. Sorry for not answering this earlier! I've added it to the milestone for the next release to indicate that we should make this error message more useful before then.

**Comment by brianhuffman** [comment]
That same error condition can arise in two situations:
* During verification, if a fresh variable declared in the post-state section is not reachable via points-to declarations from any function outputs (return value or globals)
* When applying an override, if a fresh variable declared in the pre-state section is not reachable via points-to declarations from any function inputs (arguments or globals)

I'll write a new error message that should make sense in either context.
