### ISSUE TITLE
Mutable vs readonly

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#709]
When I use `crucible_alloc_readonly` and a program tries to write to this memory region, I get a message about a memory region not being "mutable".  It would be nice if `saw` could suggest that the memory region is marked as "readonly", then that might jog my mind to think that perhaps I'm using `crucible_alloc_readonly` when I should be using `crucible_alloc`.

**Comment by weaversa** [comment]
@ChrisEPhifer Thank you!

**Comment by ChrisEPhifer** [comment]
No problem! :)
