### ISSUE TITLE
Primitive `crucible_setup_val_to_typed_term` is broken

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-script#719]
Function `setupToTerm`, which is used to implement the saw-script primitive `crucible_setup_val_to_typed_term`, appears to be defined incorrectly:
https://github.com/GaloisInc/saw-script/blob/f991bb40a0dcd3aa71296ba933aa2a08b50e9d71/src/SAWScript/Crucible/Common/MethodSpec.hs#L161-L205

Specifically, it assumes the wrong meaning for the `CrucibleElem` constructor for `SetupValue`s. In reality, `CrucibleElem` is like LLVM's `getelementptr`; it takes an argument that is a pointer to a struct or an array, and returns a pointer to a field or element. However, the code here assumes that it takes an argument that is not a pointer, but an actual array or struct literal. So if in saw-script you applied `crucible_elem` to a `crucible_array` or `crucible_struct` value (which doesn't really make sense) then `crucible_setup_val_to_typed_term` would assign the wrong meaning to the result.

EDIT: I should add that I'm looking at this function because its implementation uses `mkTypedTerm`, which I'm trying to eradicate (#718). I don't want to rewrite the definition to avoid `mkTypedTerm` while it's still wrong. Actually I'm not sure if it's even worth fixing the underlying problem, or if we should just remove `crucible_setup_val_to_typed_term` completely; it doesn't seem to be used by anything, as far as I can tell.

**Comment by robdockins** [comment]
I guess we should deprecate and remove this operation?

**Comment by brianhuffman** [comment]
Yeah, I guess deprecating it would be a good first step.
