### ISSUE TITLE
Nightly builds stopped after the 13th

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#720]
https://saw.galois.com/builds/nightly/

**Comment by weaversa** [comment]
I'd really like to try out the fixes in #717 and love that I don't have to figure out how to build `saw` :-)

**Comment by atomb** [comment]
I think merging #717 should have fixed the build. The merge happened about an hour after the build kicked off last night, so unfortunately wasn't included.

**Comment by weaversa** [comment]
Works!

**Comment by atomb** [comment]
Thanks for confirmation!
