### ISSUE TITLE
Should stack.yaml.lock be commited or ignored?

### ISSUE THREAD

**Issue by RCoeurjoly** [GaloisInc/saw-script#727]
I was about to add a PR adding stack.yaml.lock to .gitignore, but then I searched around and found that it is not so clear cut.

This file [seems ](https://stackoverflow.com/a/31629081)to [help](https://github.com/commercialhaskell/stack/issues/4795#issue-439556918) with reproducibility.

Opinions?

**Comment by brianhuffman** [comment]
Some time ago we decided to remove all `stack`-related stuff from the repository (see #988) so I'm going to close.
