### ISSUE TITLE
Unable to view SAW version

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/saw-script#73]
When I start SAW, I get output as follows:
```
$ saw
   ___  __ _ _ _ _
  / __|/ _' | | | |
  \__ \ (_| | | | |
  |___/\__,_|\_,_/ 

Loading module Cryptol
sawscript> 
```
Note the lack of version number. In contrast, running Cryptol will give you the version number:
```
$ cryptol
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.3.0 (9f3d423)

Loading module Cryptol
Cryptol> 
```
Also unlike Cryptol, there is no --version option.

SAW should probably have both of these!

**Comment by atomb** [comment]
I agree! We should have this. I'd like to add it before our next official release.
