### ISSUE TITLE
literate Cryptol imports?

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#730]
saw doesn't seem to be able to `include` literate Cryptol. Obviously this makes literate Cryptol (latex, markdown, etc.?) less useful.

**Comment by atomb** [comment]
Oh, that definitely makes it less useful! I don't expect it'd be too hard to fix.

**Comment by weaversa** [comment]
So, it appears the version of saw in the galoisinc docker image works with literate files...so maybe it’s an even easier fix

**Comment by weaversa** [comment]
Hold on...this was an `include` vs `import` mistake. saw seems to handle cryptol markdown just fine. Whoops!
