### ISSUE TITLE
"unknown record code: 2" with ffs.c and clang 7.0.2

### ISSUE THREAD

**Issue by ttaubert** [GaloisInc/saw-script#83]
When compiling ffs.c with clang v7.0.2 (on OS X 10.11.2) then it seems that SAW can't parse the LLVM bytecode and fails with:

```
Loading module Cryptol
Loading file "ffs.saw"
Extracting reference term
saw: user error (Bitcode parsing of ffs.bc failed:
unknown record code: 2
  from:
  	METADATA_BLOCK
  	MODULE_BLOCK)
```

**Comment by ttaubert** [comment]
Here's the byte code:

[ffs.bc.zip](https://github.com/GaloisInc/saw-script/files/86325/ffs.bc.zip)

**Comment by kiniry** [comment]
I presume this is the first #realworldcrypto ticket.  Thanks, Tim.  Odd that, since most of us use OS X in the office.  Someone will triage and respond soon.

**Comment by ttaubert** [comment]
> I presume this is the first #realworldcrypto ticket.

Indeed :)

**Comment by weaversa** [comment]
I'm not sure SAW supports newer releases of clang (3.7+), yet.

The advice I got in October was:
> Use the 3.6.2 MacOS prebuilt binaries from here:
> http://llvm.org/releases/download.html (further down the page a bit).

There has been a lot of focus on polishing up SAW's interface to Java, and (I think) LLVM support has lagged because of this.

**Comment by atomb** [comment]
Yes, this is known to be an issue. The bitcode parser currently only handles up through LLVM 3.6. Since Xcode now ships with a Clang that emits the 3.7 format, this is a bit of an awkward situation for many users. We plan to update the parser in the near future (and it should then support both 3.6 and 3.7).

**Comment by ttaubert** [comment]
> We plan to update the parser in the near future (and it should then support both 3.6 and 3.7).

Is there an open issue I could subscribe to?

**Comment by atomb** [comment]
If you follow this issue, we'll update it when the parser is updated. I also just added https://github.com/GaloisInc/llvm-verifier/issues/10 to track the issue for the LLVM component of SAW.

**Comment by ttaubert** [comment]
Great, thank you!

**Comment by elliottt** [comment]
Just to propagate information back, the `ffs.bc` does parse with the master branch of `llvm-pretty-bc-parser`. If there are any other examples that are currently failing to parse, I've got a bit of time available for bug fixing :)

**Comment by atomb** [comment]
I'm closing this now because this specific example does parse, and we have separate tickets for parser updates in general.
