### ISSUE TITLE
Idea: Replace `build-sandbox.sh` with Repo tool?

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#85]
Just for thought ---

replace `build-sandbox.sh` with `repo`...good idea / bad idea? Is it even possible?

https://source.android.com/source/using-repo.html

**Comment by atomb** [comment]
Interesting! I've used `repo` briefly, but not enough to really know how it works internally or exactly what features it provides, and hadn't thought of using it in this context. I think looking into it in more depth might be worthwhile. After all, the bulk of the code in the shell script portion of our our build system at this point are devoted to fetching and updating dependency repositories. Increasingly, `stack` does all the rest of the work.

**Comment by weaversa** [comment]
So, I ran across `repo` while playing with Parrot drones. They now use `repo` to build their SDK. Like you, they previously had a large script that pulled from ~10 different git repos. To see their build in action, do the following:

> `repo init -u https://github.com/Parrot-Developers/arsdk_manifests.git` (in an empty directory)
> Then run `repo sync` to get all sources
> After that, you'll be able to run `./build.sh` to build the SDK.

**Comment by atomb** [comment]
With the latest setup using Git submodules, I don't think `repo` would really buy us anything, so I'm going to close this.
