### ISSUE TITLE
When Java method doesn't exist, the list of existing methods reported by crucible_jvm_verify is wrong

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#911]
When running `crucible_jvm_verify` on, for example, the method key `add(Ljava/math/BigInteger;Ljava/math/BigInteger;)Ljava/math/BigInteger;` from `java.math.BigInteger`, I get the following:

````
ExecException unknown Could not find method
add(Ljava/math/BigInteger;Ljava/math/BigInteger;)Ljava/math/BigInteger;
in class java.math.BigInteger.
Available methods: "<clinit>"
"<init>" "clone" "equals"
"finalize" "getClass" "hashCode"
"notify" "notifyAll"
"registerNatives" "toString"
"wait" "wait" "wait" "Please check that the class and method are correct."
````

It looks like it's perhaps jumping one level too high in the class hierarchy and listing the methods of the parent class (`java.lang.Object` in this case)?

**Comment by brianhuffman** [comment]
Yes, I know exactly what's wrong here. Obviously I didn't test this code thoroughly enough. If no matching methods are found in a class, and the class has a superclass, then the search forgets about the original class and calls itself again on the superclass. But if it runs out of superclasses and never finds anything, it only lists the methods for the last class in the chain (`java.lang.Object` in your case). Instead, it should backtrack to the beginning and list all the available methods for all classes in the chain.

**Comment by brianhuffman** [comment]
Probably the easiest way to get the behavior we want is for the inner function of `findMethod` to take an extra accumulating parameter that remembers the set of method names that it has passed over so far. Then if we get to the end and find no matching methods, we will have the entire list on hand to print out.
