### ISSUE TITLE
Indexing a SAW tuple with 0 causes crash

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/saw-script#94]
Observe:
```
$ saw
   ___  __ _ _ _ _
  / __|/ _' | | | |
  \__ \ (_| | | | |
  |___/\__,_|\_,_/ 

Loading module Cryptol
sawscript> let a = (1,2)
sawscript> a.1
1
sawscript> a.2
2
sawscript> a.0
saw: Prelude.!!: negative index
$ 
```
Presumably exiting SAW isn't the intended reaction.

Also, haven't we settled on zero-based indexing? (GaloisInc/cryptol#82)

**Comment by weaversa** [comment]
I agree that `saw` tuple indexing and `cryptol` tuple indexing should be the same. As well, zero based indexing helps avoid these bugs.
