### ISSUE TITLE
Cannot disable ANSI output

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-script#957]
Whether or not I have the `--no-color` option set, when I run SAW inside emacs using `saw-script.el`, every `print_goal` command's output is festooned with ANSI sequences around names.  So I see things like `^[[0mPrelude.not^[[0m`.  I'm not sure if this is an error in saw-script, or in saw-script.el.

**Comment by brianhuffman** [comment]
The ANSI output is supposed to be off by default; it should only be enabled if you use `set_color true`.

I actually had not been aware of the `--no-color` option before; according to `CHANGES.md` it says it's for printing the ASCII-art "SAW" logo without color codes. We should probably make the term pretty-printing code check the `--no-color` flag as well, and if present it should suppress the ANSI codes even if `set_color` is enabled.

**Comment by msaaltink** [comment]
If I add `set_color true` I got codes other than `[0m`, but `set_color false` does not eliminate the `^[[0m` codes I see in the output.

**Comment by brianhuffman** [comment]
Ok, I just looked into this a bit more deeply. It is related to our recent switch to the `prettyprinter` library (GaloisInc/saw-core#106). I expected that using the "empty" annotation would result in no ANSI codes being output, but apparently that's not the case. I'll have to come up with another workaround for that.

**Comment by andreistefanescu** [comment]
in the meantime, I use sed to clean up the output: `sed -i 's/\x1b\[[0-9;]*m//g' out.txt`
