### ISSUE TITLE
Make release builds have cleaner version numbers

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#982]
The released versions of 0.6 and 0.7 have banners like the following:

````
 ┏━━━┓━━━┓━┓━┓━┓
 ┃ ━━┓ ╻ ┃ ┃ ┃ ┃
 ┣━━ ┃ ╻ ┃┓ ╻ ┏┛
 ┗━━━┛━┛━┛┗━┛━┛ version 0.7 (670e349-dirty)



sawscript>
````

This includes the commit hash and the string `dirty` indicating that it's not just a clean checkout of the repository. We should fix this before releasing 0.8.

**Comment by sauclovian-g** [comment]
For the record, the current behavior in 1.3 is now:
```
 ┏━━━┓━━━┓━┓━┓━┓
 ┃ ━━┓ ╻ ┃ ┃ ┃ ┃
 ┣━━ ┃ ╻ ┃┓ ╻ ┏┛
 ┗━━━┛━┛━┛┗━┛━┛ version 1.3 (4ff3ce115 release-1.3)

sawscript> 
```
