### ISSUE TITLE
Add support for tuple patterns

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#99]
Right now, the only way to extract elements from a tuple is with positional selectors (`x.0`, etc.). It would be nice to allow pattern matching syntax, too, so you could do, for instance:
```
let f (x, y) = ...
```
or
```
(a, b) <- ...
```
and so on.

**Comment by brianhuffman** [comment]
Commit 46c4fc4 adds support for the forms of tuple binders mentioned above, as well as lambda binders like `\(x, y) -> e`. Support for declarations with pattern bindings like `let (a, b) = ...` is still missing, though. I'll close the ticket once I've implemented that as well.
